### PR TITLE
build(craft): Enable automatic Changelogs

### PR DESCRIPTION
**Pull request by BYK**

### CODE REVIEW

**Comment by BYK** [comment]
Also /cc @chadwhitacre

**Review by evanh — APPROVED** [review]
Thanks BYK!

**Comment by BYK** [comment]
@evanh we'll need that `/gcbrun` again as I had to update the patch from master 😅

**Comment by BYK** [comment]
pls merge me? @evanh ? :D

**Comment by evanh** [comment]
> pls merge me? @evanh ? :D

I'll watch it!

**Pull request merged**
