### PR TITLE
ref(tests): Make `tests` a package

### PR DESCRIPTION
**Pull request by tkaemming**
This allows it to be importable by mypy.

This also makes all `test.*` imports absolute because otherwise tests won't run for some reason I don't care to figure out.

## Test Plan

They still run, imports into `tests.fixtures` no longer report as `Any` with `reveal_type` when type checking.

### CODE REVIEW

**Comment by tkaemming** [comment]
I tried to do this with #508 but it broke all the tests. Since it required so many changes to the test directory I figured it made sense to submit as a separate change.

**Comment by tkaemming** [comment]
I also left these imports intentionally as-is (unsorted) but can sort them if anybody has any strong preference.

**Comment by tkaemming** [comment]
😡

**Review by lynnagara — APPROVED** [review]
Seems good to me

**Pull request merged**
