### PR TITLE
feat(migrations): Support reversing migrations

### PR DESCRIPTION
**Pull request by lynnagara**
Add the ability to run a migration in reverse.
Also runs all of the reverse migrations in tests.

### CODE REVIEW

**Comment by fpacifici** [comment]
High level question. I cannot remember if we documented, one month ago, the discussions around which migration would be allowed to rollback and under which circumstances. 
1) Are we planning to allow reverting anything no matter which state a migration is in? Like reverting completed migrations. I remember we discussed whether we should allow a rollback only of migrations that where in an inconsistent state in order to go back to a consistent one.
2) What about migrations that cannot be safely reverted. Like removing a column that was not empty or a non reversible data migration?

**Comment by lynnagara** [comment]
oops

**Comment by lynnagara** [comment]
We previously said that it wouldn't be allowed at all once a migration is completed (to avoid dealing with the problems you listed above). Though I am not 100% sure there's not a valid use case for allowing this (with `--force` and lots of warnings) in case someone gets into a weird state

**Comment by fpacifici** [comment]
Ok, so who would be responsible to validate that, when run_migration is called with reverse=True the migration can only be executed with --force if it was already completed ? Is this responsibility going to be on the caller of run_migration ?

**Comment by lynnagara** [comment]
I'm not 100% certain yet - either the caller of run migration beforehand or run_migration itself will also get passed the `force` parameter. Running blocking migrations will likely have a similar flow and potentially respect the same `force` parameter.

**Comment by fpacifici** [comment]
Mind writing a comment or TODO providing some context about how this is supposed to work and about the restrictions ?

**Review by fpacifici — APPROVED** [review]

**Pull request merged**
