### PR TITLE
Allow configuring kafka sasl parameters

### PR DESCRIPTION
**Pull request by cragonnyunt**
This PR allows snuba to connect to kafka brokers protected by sasl plaing username/password. The setting was initially introduced in #1406 but the author decided to remove in the end. 

Benefits for docker and kubernetes users - when I use the chart https://github.com/sentry-kubernetes/charts for deployment, the snuba scripts can't connect to external kafka brokers as sasl username/password can't be set via env. There is no need to turn off sasl protection of kafka, if it can be set via environment variables. 

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Review by lynnagara — APPROVED** [review]

**Comment by cragonnyunt** [comment]
After investigating the pipeline failure, I found the default value for `sasl.mechanism` is not empty text, it is set to `GSSAPI`. 

Ref - https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md

**Comment by cragonnyunt** [comment]
It looks like transient failure in CI pipeline, please make it re-run again?

**Pull request merged**
