### PR TITLE
ref(spans): Refactor spans Rust processor

### PR DESCRIPTION
**Pull request by phacops**

### CODE REVIEW

**Review by lynnagara — APPROVED** [review]

**Comment by lynnagara** [comment]
It may be worth to check some of these payloads into sentry-Kafka-schemas, they get run against both python and rust processors that way. But totally up to you.

**Comment by untitaker** [comment]
oh. oops. i thought i could deploy snuba with this and see if it fixes the crashloop, but snuba deploys are paused today

**Comment by phacops** [comment]
Are you suggesting these tests are not that useful and I should just add examples in `sentry-kafka-schemas` instead?

**Comment by phacops** [comment]
> oh. oops. i thought i could deploy snuba with this and see if it fixes the crashloop, but snuba deploys are paused today

Crashloop was fixed already https://github.com/getsentry/snuba/commit/6c48b4e13d9781a0f7bc2266352b75c5b97f9366.

**Pull request merged**
