### PR TITLE
ref(settings): Enable query cache by default

### PR DESCRIPTION
**Pull request by tkaemming**
Redis is already required by virtue of replacement state, so I'm not sure what other benefits we would get from this being disabled in the default configuration. There is possibly an argument to be made against its use in development, but that seems like the special case, not the common one.

We might also want to reconsider the default value for the `cache_expiry_sec` dynamic configuration — it's also set at 1 second which seems extremely low for any practical use case.

If we don't want to do this for some reason, we should change so that deduplication is off by default — right now the default is on, which is the worst of both worlds.

### CODE REVIEW

**Comment by fpacifici** [comment]
Cannot see any reason for not doing this:
- sentry tests and snuba tests already have caching enabled so they cannot break due to this
- on prem already needs redis.
Will let James chime in on prod, otherwise it is good to me.

**Review by JTCunning — APPROVED** [review]
🍪

**Comment by tkaemming** [comment]
FYI @BYK this changes the defaults for on-premise. This shouldn't require any services or setup steps that aren't already.

**Comment by BYK** [comment]
>FYI @BYK this changes the defaults for on-premise.

Would that affect anyone upgrading Snuba/Sentry?

**Comment by tkaemming** [comment]
I don't think so, no. Redis is already a requirement, this just adds another place that it is used.

**Pull request merged**
