### PR TITLE
fix(arroyo): Tag all consumer metrics by the smallest partition index

### PR DESCRIPTION
**Pull request by untitaker**
INC-588 INC-581

This should help us identify pod-specific problems, such as one
partition lagging behind another.

Ideally arroyo should do this, but it's easier here because arroyo has
no concept of global tags.

### CODE REVIEW

**Comment by loewenheim** [comment]
Is `create_with_partitions` ever called with nonempty partitions outside of a test?

**Comment by untitaker** [comment]
> Is create_with_partitions ever called with nonempty partitions outside of a test?

it shouldn't be, i just wanted to avoid any potential exceptions

**Review by loewenheim — APPROVED** [review]

**Comment by lynnagara** [comment]
Is the existing instance id tag insufficient?

**Comment by untitaker** [comment]
> Is the existing instance id tag insufficient?

it doesn't exist, and we want to attribute arroyo metrics to specific partitions

**Review by MeredithAnya — APPROVED** [review]
This makes sense to me

**Pull request merged**
