### PR TITLE
fix(generic-metrics): Update default `decasecond_retention_days` and `min_retention_days` columns for distributions

### PR DESCRIPTION
**Pull request by john-z-yang**
### Stack PR Chain

| PR                                                   | Changes                                                  | Status        | Branch From                                          |
| ---------------------------------------------------- | -------------------------------------------------------- | ------------- | ---------------------------------------------------- |
| [#1](https://github.com/getsentry/snuba/pull/4780) | ➤ Update default `decasecond_retention_days` and `min_retention_days` columns for distributions | In review          | Master                                               |
| [#2](https://github.com/getsentry/snuba/pull/4782) | Update default `decasecond_retention_days` and `min_retention_days` columns for sets | In review | [#1](https://github.com/getsentry/snuba/pull/4780) |
| [#3](https://github.com/getsentry/snuba/pull/4781) | Update default `decasecond_retention_days` and `min_retention_days` columns for counters | In review | [#2](https://github.com/getsentry/snuba/pull/4782) |

### Overview

Updates the default values for `decasecond_retention_days` and `min_retention_days` columns to 30 and `retention_days`

### CODE REVIEW

**Comment by nikhars** [comment]
Is there a way to get the desired retention for the product team without modifying the default retention days? If we are modifying the default for 10s to 30 days, I would expect that the default retention days for 1 min should be higher than that maybe 60 days. And then there is a ripple effect of having increased default retention days.

Is the change necessary because of the condition we use in the materialized views?

**Comment by john-z-yang** [comment]
> Is there a way to get the desired retention for the product team without modifying the default retention days? If we are modifying the default for 10s to 30 days, I would expect that the default retention days for 1 min should be higher than that maybe 60 days. And then there is a ripple effect of having increased default retention days.
> 
> Is the change necessary because of the condition we use in the materialized views?

The change is not necessary, the main reason I am changing it is because they are not consistent across the tables.

We can control this by updating the consumer to write to that column directly, like what we are doing with minute granularity (the default is 30 days but are we writing `retention_days` to it). I just wanted a reasonable value for them so they're all on the same page. Another option is just set everything to `retention_days` by default, and write our own values to it.

**Comment by nikhars** [comment]
> Not at all, The main reason I am changing it is because they are not consistent across the tables, and it could get confusing. (I think the retention days for the other ones are all `retention_days`). I just wanted a reasonable value for them so they're all on the same page. Another option is just set everything to `retention_days` by default, and write our own values to it.

I see. Yeah having a consistent behavior across all types of metrics is desirable. What if we changed the other tables like `sets` and `counters` to have their defaults as they are present today on the distributions table? I believe the values on the distributions table make a lot of sense to me. What do you think?

**Comment by john-z-yang** [comment]
> > Not at all, The main reason I am changing it is because they are not consistent across the tables, and it could get confusing. (I think the retention days for the other ones are all `retention_days`). I just wanted a reasonable value for them so they're all on the same page. Another option is just set everything to `retention_days` by default, and write our own values to it.
> 
> I see. Yeah having a consistent behavior across all types of metrics is desirable. What if we changed the other tables like `sets` and `counters` to have their defaults as they are present today on the distributions table? I believe the values on the distributions table make a lot of sense to me. What do you think?

Right now for distributions we have
7 days retention for 10 sec
30 days retention for 60 sec

For the others (sets/counters) we have
`retention_days` days retention for 10 sec
`retention_days` days retention for 60 sec

The migration proposed in this pr
30 days retention for 10 sec
`retention_days` days retention for 60 sec


I'm not sure how I feel applying 30 days retention for 60 sec, since we are manually writing `retention_days` to that column after we floated the idea of 30 days retention. Same goes with setting 7 days for 10 sec, because DDM will want 30 days. 
So we will need to manually write 30 to 10 sec retention days and `retention_days` to 60 sec retention days if we change all the other tables to be the same as distribution.


With migration proposed in this pr we don't need to write any values. But I honestly don't feel very strongly either way, I just want them to be the same, let me know what you think!

**Comment by nikhars** [comment]
> With migration proposed in this pr we don't need to write any values.

My current thinking is along these lines. The clickhouse tables should have sane defaults. Defaults are just an idea of the action which needs to be applied if a column is empty. Whether an application relies on the default behavior or not is configurable. But the rules for applying restrictions should be standardized. In this specific scenario, the question is whether all metrics should always write some values for each granular retention or only provide overrides. If our defaults are not going to be sane, like the 10s granularity taking 30days by default, then where would the restriction of a metric being added needing a 10s granularity with a default retention of 7 days be enforced?

**Comment by john-z-yang** [comment]
> > With migration proposed in this pr we don't need to write any values.
> 
> My current thinking is along these lines. The clickhouse tables should have sane defaults. Defaults are just an idea of the action which needs to be applied if a column is empty. Whether an application relies on the default behavior or not is configurable. But the rules for applying restrictions should be standardized. In this specific scenario, the question is whether all metrics should always write some values for each granular retention or only provide overrides. If our defaults are not going to be sane, like the 10s granularity taking 30days by default, then where would the restriction of a metric being added needing a 10s granularity with a default retention of 7 days be enforced?

That make sense to me, I will be closing this pr, and update the pr that change the other tables

**Pull request closed without merging**
