### PR TITLE
fix(tests): Make sure child process actually exits cleanly

### PR DESCRIPTION
**Pull request by tkaemming**
…

### CODE REVIEW

**Comment by tkaemming** [comment]
Turns out the `time.sleep` in this code isn't enough to do anything useful, since the consumer is still importing everything when SIGINT is sent. The consumer signal handler isn't even attached yet.

**Comment by tkaemming** [comment]
Thinking about this more, I think we should just get rid of this test. The only value that I can see this test providing is that the command line argument/option definition itself is valid. I don't know as we need to test this (if my understanding of the deploy process is correct, if these commands exit non-zero during the deploy, the deploy will stop, making this a relatively low impact scenario), but if we do think this is valuable, we can get the same (or better) level of confidence by just importing `snuba.cli` or adding `--help` to this command if we really need to test that this will work correctly as an entrypoint in a clean environment.

I think we should come up with _something_ to exercise the paths within the `snuba consumer` command (I think that this is the only test that covers the `ConsumerBuilder` at all, and it doesn't seem to be guaranteed to deterministically reach that path at this point), but I'm not really sure what the appropriate scope or level of abstraction is for that kind of test. In its current implementation, anything calling the `ConsumerBuilder` _must_ be an integration test (due to the Kafka dependency), and the state space is so large at that point that writing a good test seems impractical.

**Comment by fpacifici** [comment]
There is a way to unit test click scripts:
https://click.palletsprojects.com/en/7.x/testing/#basic-testing

So we could replace that test with the click unit test. This should be quick to achieve. Not sure how this works with signals though.

**Comment by tkaemming** [comment]
That looks fine, but I don't really see how that materially changes anything noted in this comment: https://github.com/getsentry/snuba/pull/644#issuecomment-567132805

**Comment by vladkluev** [comment]
quitely closing because it's 2 years old

**Pull request closed without merging**
