### PR TITLE
fix AssertionError in snuba 0006_sorting_key_change migration

### PR DESCRIPTION
**Pull request by wolandspb**
If timestamp already DateTime CODEC(T64, ZSTD(1)) migration fails.

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by wolandspb** [comment]
I had the same issue as https://github.com/getsentry/snuba/issues/6186
This PR should fix it.

**Comment by wolandspb** [comment]
Hi, @evanh can u check this?

**Comment by wolandspb** [comment]
Thanks a lot, @MeredithAnya!
Is it possible to you to check this PR too: https://github.com/getsentry/sentry/pull/81902. Its not related, but since you have CI issues Im afraid that this will can take a while too.

**Comment by MeredithAnya** [comment]
> Thanks a lot, @MeredithAnya! Is it possible to you to check this PR too: [getsentry/sentry#81902](https://github.com/getsentry/sentry/pull/81902). Its not related, but since you have CI issues Im afraid that this will can take a while too.

That PR is out of scope for my team, so I don't really have control over when it will get looked at, but I can let other folks know.

**Comment by wolandspb** [comment]
> but I can let other folks know

That would be awesome, thanks!

**Pull request closed without merging**
