### PR TITLE
fix(admin): Remove build output from repo

### PR DESCRIPTION
**Pull request by rahul-kumar-saini**
Every time we build the front end, a new `build.js` file is created and clutters the PR.

### CODE REVIEW

**Comment by lynnagara** [comment]
So what's the plan? Are you going to create a GitHub action to build the file?

**Comment by rahul-kumar-saini** [comment]
Oops, I assumed when this is deployed it builds from scratch and the build files were just accidentally committed. If that's not the case I can try to figure out how build+deploys work with GitHub actions.

**Review by lynnagara — CHANGES_REQUESTED** [review]
This is needed since we haven't built the deployment pipeline for prod yet that builds the javascript file.

**Comment by rahul-kumar-saini** [comment]
Closing as this requires build step built into CI for admin console.

**Pull request closed without merging**
