### PR TITLE
feat: Add hierarchical_hashes column to errors (migrations only)

### PR DESCRIPTION
**Pull request by untitaker**
Migrations from #1687 split out into separate PR.

### CODE REVIEW

**Comment by untitaker** [comment]
Not sure how to proceed. I am fairly certain that adding the columns to the schema will include them in all sorts of queries, such as the ones also done by the replacer.

**Comment by fpacifici** [comment]
You are right (damn). This process does not work anymore this way since when we enforced the schema to be in line with the result of the migrations. And you cannot update the schema otherwise replacements would assume it is in prod. We did not add anything to errors/events since so we never noticed.

I think the only way is to run the DDL in prod first and then merge the migration PR. Up to you if you want to keep it in a separate PR or not, sorry for the inconvenience.
We will fix the process.

**Comment by untitaker** [comment]
I can also patch away the testcase in the migrations PR and later revert if
it helps

**Comment by untitaker** [comment]
Also it just occurred to me that it may be fine to let the consumers crash.
It is not pretty but the crash loop will be over once the migration is done.

**Comment by fpacifici** [comment]
"it may be fine to let the consumers crash." no this is definitively not ok. 
schema/consumer change must always be 100% deploy safe as we cannot synchronize a deployment with a DDL change.

**Comment by lynnagara** [comment]
Like @fpacifici mentioned earlier, the way to go is to manually apply in prod first before merging this. Any other environments we need to support stop replacers while running migrations.

**Comment by lynnagara** [comment]
Heads up, MultiStepMigration is renamed to ClickhouseNodeMigration on master so you'll need to rename here too before merging. Sorry for the inconvenience.

**Comment by untitaker** [comment]
closing this in favor of #1687

**Comment by untitaker** [comment]
Who can help me with applying DDL?

**Comment by fpacifici** [comment]
James has this scheduled for tomorrow.

**Comment by JTCunning** [comment]
Done.

**Pull request closed without merging**
