### PR TITLE
allow an override configuration file for connecting to Kafka

### PR DESCRIPTION
**Pull request by ChannyClaus**
Related to https://github.com/getsentry/snuba/issues/1337

It still seems not possible to configure `kafka` parameters for `snuba bootstrap` entrypoint. This change allows the user to provide a JSON file to override the default configuration for `kafka`.

### CODE REVIEW

**Comment by fpacifici** [comment]
Hi,
thanks for the contribution, though parameters override should now be possible.
It was implemented in https://github.com/getsentry/snuba/pull/1406

Parameters per broker are set in Snuba settings: https://github.com/getsentry/snuba/blob/master/snuba/settings/__init__.py#L85-L88
There is a list of allowed parameters, but that can be easily extended. Which parameters would you like to override ?

**Comment by ChannyClaus** [comment]
You're absolutely right - I was able to get it to work.

On a related note, how does `snuba` pick up the overrode setting exactly? I'm using `helm` chart on https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/configmap-snuba.yaml, which seems to be mounted as `settings.py` in the container, which then subsequently gets picked up by `snuba` executable.

Either way, sorry for the noise. Thanks for taking a look.

**Comment by fpacifici** [comment]
Hi,

This is the logic that picks up the override config file 
https://github.com/getsentry/snuba/blob/master/snuba/settings/__init__.py#L146-L180

- there are defaults in that file.
- the client can provide an override file
- The directory to pick up the file can be defined with the SNUBA_SETTINGS environment variable
- the file to load can be defined as an absolute path or as a logical name like `test` or `prod` then Snuba will expect `settings_test.py` or `settings_prod.py`

I am not familiar with the repo you linked though it seems to be defining the environment variable here 
https://github.com/sentry-kubernetes/charts/blob/9c8c7fb58e384ba2837f4624f4831cbdb118cd2b/sentry/templates/_helper.tpl#L389-L390

**Comment by ChannyClaus** [comment]
ah, missed that portion of the file. makes a lot of sense. thanks again!

also currently trying to get this to work for `relay` as well - hopefully it already allows configuring the kafka connection over tls...

**Pull request closed without merging**
