### PR TITLE
Update cluster.py to fix not honoring max_connections in config

### PR DESCRIPTION
**Pull request by bkk-bcd**
Right now the latest helm charts (22.2.0) deployments are pretty much completely broken because of this. See issue below for details. Probably been broken for  quite a while; I imagine a given ingestion load has a lot to do with whether it shows up or not for a particular install...

Fixes https://github.com/getsentry/snuba/issues/5775

### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by rdziwinski** [comment]
Hi :)
Thanks for fixing. Generally this problem has been known for a long time -> https://github.com/getsentry/snuba/issues/4596
I hope it will be release ASAP :)

**Comment by bkk-bcd** [comment]
> Hi :) Thanks for fixing. Generally this problem has been known for a long time -> #4596 I hope it will be release ASAP :)

🤞

**Comment by volokluev** [comment]
This is already there:

https://github.com/getsentry/snuba/pull/5795/files#diff-7df145bde25ca970ceb9ba5c6fd95515b040310b905d4bfc9fc1e09b6e3eafa2L408

**Comment by volokluev** [comment]
Dupe of https://github.com/getsentry/snuba/pull/5794

**Comment by bkk-bcd** [comment]
Doh! Beaten to the punch.

**Pull request closed without merging**
