### PR TITLE
fix(monitoring): Add dataset tag to bytes scanned metric

### PR DESCRIPTION
**Pull request by enochtangg**
This PR is responsible for adding missing dataset tag to the new bytes scanned metric.

### CODE REVIEW

**Review by volokluev — COMMENTED** [review]
I'm not sure I want to update the interface to all these policies just for this reporting, the storage is already there as a tag, what is the reason for adding dataset?

**Comment by enochtangg** [comment]
@volokluev That's fair. I was comparing our old dashboard for bytes scanned and it contained dataset tag so I was looking to consolidate. Maybe the storage_key is sufficient. It just takes a little bit more mental energy to switch contexts since cumulative time dashboard is grouped by dataset.

**Comment by volokluev** [comment]
which dashboard are you looking at?

**Comment by enochtangg** [comment]
There are a few. Let's discuss offline so I can avoid sharing DD links.

**Pull request closed without merging**
