### PR TITLE
feat(TDC): Create transactions dataset config file

### PR DESCRIPTION
**Pull request by enochtangg**
Changes made:
* Transactions dataset converted to .yaml

### CODE REVIEW

**Review by lynnagara — DISMISSED** [review]

**Comment by lynnagara** [comment]
The comment says `Transactions dataset converted to .yaml` but this seems like it's only adding the yaml version not converting anything. When is the old version going to be deleted?

**Comment by lynnagara** [comment]
@enochtangg If both exist, can you please confirm which one is the one that actually applies in prod and which is the one that is ignored?

**Comment by evanh** [comment]
> which one is the one that actually applies in prod

We are defaulting to using configuration versions of Datasets in production.

> or do we want to keep it for some reason?

We've been preserving these initial Python versions so we can more easily roll back if an issue happens.

**Comment by lynnagara** [comment]
Ok. Are those __init__ files needed in yaml land?

**Comment by rahul-kumar-saini** [comment]
https://github.com/getsentry/snuba/blob/master/tests/datasets/configuration/test_dataset_loader.py
This can probably be extended to cover the additional dataset like the [entity loader test](https://github.com/getsentry/snuba/blob/master/tests/datasets/configuration/test_entity_loader.py#L41) was extended to cover the new transactions entity.

**Comment by enochtangg** [comment]
Attempted to do some Git magic and ended up deleting this by accident, created a new PR here: https://github.com/getsentry/snuba/pull/3280

**Pull request closed without merging**
