### PR TITLE
fix: Add request context indexing

### PR DESCRIPTION
**Pull request by markstory**
Discover and issue search currently offer three fields, `http.method`, `http.referer`, and `http.url`. All of these fields are mapped to `contexts[http.*]` by the column resolver, however none of these fields currently work.

In errors, the http_method and http_referer fields are indexed as promoted context data, but are not in the promoted_context mapping and so they are never found by context expression expansion. For transactions, the http fields were simply not indexed.

I've added the http.url field to the events dataset, and added both the request and http contexts to errors and transactions. The errors dataset has the request interface indexed as `request` so I've included that key on transactions with the goal of ending up on that alias when errors goes live.

### CODE REVIEW

**Comment by fpacifici** [comment]
I am not sure I get exactly why we are solving this by using contexts. 
I get that the column resolver today tries to use contexts, but is the event supposed to have the content of the request interface stored in contexts? The public events payload documentation shows the request interface as a top level concept and does not show a request context.
https://develop.sentry.dev/sdk/event-payloads/request/
https://develop.sentry.dev/sdk/event-payloads/contexts/

So I guess we should figure out where these are supposed to be stored before moving them into contexts. Where is the request interface in nodestore? The event loaded from nodestore should behave i a compatible way. Do you have ay context around this?

Then, if we decide to add columns, the procedure to do that is different. We cannot add the column and start using it in the same PR.
1) the column needs to be added to the schema here (and a migration has to be provided). PR
2) the column needs to be added in production separately
3) then we can make the changes to the message processor to start filling it. PR
4) then we need to address the query path depending on how we want to expose the column (context/promoted context/individual column)

**Comment by markstory** [comment]
> So I guess we should figure out where these are supposed to be stored before moving them into contexts. Where is the request interface in nodestore? The event loaded from nodestore should behave i a compatible way. Do you have ay context around this?

In nodestore, the request interface is stored as a top level interface like `user`, `sdk`, or `exception`.

> I am not sure I get exactly why we are solving this by using contexts.

I saw that the request interface was indexed into contexts in the errors dataset https://github.com/getsentry/snuba/blob/d008d344064a4527aafb1ec4579e3b02f1229287/snuba/datasets/errors_processor.py#L70-L79

Because errors is the second revision of the error event storage, I inferred (perhaps incorrectly) that this was the preferred way to store request interface data and modeled these changes to match the implementation in errors.

I'm happy to add additional columns to transactions and events to store this data if that is preferred. Should errors also be changed?

**Comment by fpacifici** [comment]
Yes, this is weird. I am not sure what the reason was for storing the content of the request interface into contexts, let me investigate a bit on this.

**Comment by markstory** [comment]
Going to close this as @evanh is working on a better solution.

**Pull request closed without merging**
