### PR TITLE
ref(spans): Remove unused module column

### PR DESCRIPTION
**Pull request by phacops**
This column is not populated and not used in the frontend anymore and should be removed.

### CODE REVIEW

**Review by evanh — COMMENTED** [review]
Can you split the migration into a separate PR from the other changes (config/consumer)?

**Comment by phacops** [comment]
> Can you split the migration into a separate PR from the other changes (config/consumer)?

So, what exactly do I need to separate here? Since the column is not nullable, wouldn't insertion fail if I change the consumer? So, I can leave a default empty value for that, but then, do I need to keep it in the storage config as well?

**Comment by phacops** [comment]
Migration moved to https://github.com/getsentry/snuba/pull/5792.

**Comment by phacops** [comment]
@evanh I added back to the processor the `module` field with an empty string value to be inserted into ClickHouse since the column is not nullable, inserts would fail if I didn't, right?

**Comment by evanh** [comment]
> @evanh I added back to the processor the `module` field with an empty string value to be inserted into ClickHouse since the column is not nullable, inserts would fail if I didn't, right?

You added that here? If the column doesn't exist, why do you need to write to it?

**Pull request closed without merging**
