### PR TITLE
feat(discover): Add _tags_hash_map and deleted columns to merge table

### PR DESCRIPTION
**Pull request by lynnagara**
This migration adds two columns to the Discover merge table:
- `_tags_hash_map`, which allows use to use the same tags optimization
as errors and transactions
- `deleted`, which allows us to properly excluded deleted errors

The migration statements that this generates are:
```
ALTER TABLE discover_local ADD COLUMN IF NOT EXISTS _tags_hash_map Array(UInt64) AFTER tags;
ALTER TABLE discover_local ADD COLUMN IF NOT EXISTS deleted UInt8 AFTER contexts;
ALTER TABLE discover_dist ADD COLUMN IF NOT EXISTS _tags_hash_map Array(UInt64) AFTER tags;
ALTER TABLE discover_dist ADD COLUMN IF NOT EXISTS deleted UInt8 AFTER contexts;
```

### CODE REVIEW

**Comment by lynnagara** [comment]
Migrations generated:

```
ALTER TABLE discover_local ADD COLUMN IF NOT EXISTS _tags_hash_map Array(UInt64) MATERIALIZED arrayMap((k, v) -> cityHash64(concat(replaceRegexpAll(k, '(\\=|\\\\)', '\\\\\\1'), '=', v)), tags.key, tags.value) AFTER tags;
ALTER TABLE discover_dist ADD COLUMN IF NOT EXISTS _tags_hash_map Array(UInt64) AFTER tags;
```

**Review by fpacifici — APPROVED** [review]
You may want to double check that you can materialize columns on a merge table instead of relying on the materialization on the local tables as we do for the distributed table.

**Comment by lynnagara** [comment]
A couple of changes here since this was last reviewed:
- Removed the materialization on tags hash map (though possible, it doesn't add any value)
- Added migration statement to add the `deleted` column as well

**Review by evanh — APPROVED** [review]
LGTM.

**Comment by lynnagara** [comment]
This has been applied in prod

**Pull request merged**
