### PR TITLE
feat(suspect-spans): Change exclusive time to Float32

### PR DESCRIPTION
**Pull request by Zylphrex**
Using Float32 is enough precision for the exclusive time column. Dropping the
original column and starting over. This column is only internal at the moment so
it is safe to drop any existing data. Before dropping the column, make sure the
`input_format_skip_unknown_fields` option is enabled and/or the processors are
not emitting the span columns to avoid errors in the transaction processors.
Additionally, make sure that `materialize_ttl_after_modify` is disabled prior
modifying the TTL to avoid massive merges.

# Forwards

```sql
Local operations:
ALTER TABLE transactions_local ADD COLUMN IF NOT EXISTS spans.exclusive_time_32 Array(Float32) AFTER spans.group;
ALTER TABLE transactions_local MODIFY COLUMN spans.exclusive_time_32 Array(Float32) TTL finish_ts + INTERVAL 1 MONTH;


Dist operations:
ALTER TABLE transactions_dist ADD COLUMN IF NOT EXISTS spans.exclusive_time_32 Array(Float32) AFTER spans.group;
```

# Backwards

```sql
Local operations:
ALTER TABLE transactions_local DROP COLUMN IF EXISTS spans.exclusive_time_32;


Dist operations:
ALTER TABLE transactions_dist DROP COLUMN IF EXISTS spans.exclusive_time_32;
```

### CODE REVIEW

**Comment by Zylphrex** [comment]
Unsure how we typically enable these options, but the `input_format_skip_unknown_fields` option can be enabled via #2232 2232

**Comment by evanh** [comment]
@fpacifici I see https://github.com/getsentry/ops/pull/4092 is still open. I think we disabled `materialize_ttl_after_modify` manually though right?

**Comment by fpacifici** [comment]
We did not, we have to manually disable it every time we run a DDL operation

**Review by evanh — APPROVED** [review]
This all looks good to me. We'll have to wait until next week to deploy though.

**Pull request merged**
