### PR TITLE
fix(rust): Use the right origin timestamp for functions

### PR DESCRIPTION
**Pull request by phacops**

### CODE REVIEW

**Review by untitaker — APPROVED** [review]

**Comment by lynnagara** [comment]
I noticed that timestamp is mandatory in the schema but is Option<u64> here, should we align these?

**Comment by phacops** [comment]
Yes, correct, I pushed a commit for that as you were commenting on it.

**Comment by lynnagara** [comment]
I mean `msg.timestamp` (as well as `msg.received`)

**Comment by lynnagara** [comment]
https://github.com/getsentry/sentry-kafka-schemas/blob/main/schemas/profile-functions.v1.schema.json#L68

**Comment by phacops** [comment]
Oh, I see. Good point.

**Pull request merged**
