### PR TITLE
fix(discover): Additional handling for date time literals

### PR DESCRIPTION
**Pull request by Zylphrex**
Conditions on the timestamp can be generated from discover as
`["less", ["timestamp", "2020-01-01T00:00:00.000000Z"]]` in a boolean search.
However, only top level conditions using infix operators have been special
cased to parse the date time literal as a Literal whereas this is parsed as a
Column when nested in a boolean search. This change updates the timeseries
processor in order to match and process this particular use of date time
literals correctly.

### CODE REVIEW

**Review by evanh — APPROVED** [review]
This looks good to me. Please make sure to run the sentry tests against this change as well.

**Comment by fpacifici** [comment]
This would apply only to entities that use the timeseries processor (not all of them). Is this intended ? Other can have datetime columns as well.

**Comment by Zylphrex** [comment]
> This would apply only to entities that use the timeseries processor (not all of them). Is this intended ? Other can have datetime columns as well.

I took a look and I don't see any entities that are not using the timeseries processor. Is your concern that it is possible an entity can exist that does not use the timeseries processor?

The intent behind this change is to allow the existing timeseries processor to handle this specific usage of date time literals that are currently being parsed as Columns when they should not. And thus should only affect entities that are using the timeseries processor.

**Comment by fpacifici** [comment]
Actually there are two issues here.
1) `["less", ["timestamp", "2020-01-01T00:00:00.000000Z"]]`  is an invalid expression in the snuba language and a validator is missing there to reject the query. `"2020-01-01T00:00:00.000000Z"` literally means that column name, which is not a valid column name. In order for that expression to be parsed as literal the correct way is this: `["less", ["timestamp", "'2020-01-01T00:00:00.000000Z'"]]`.
Now that would be correctly a string literal. Literals in expressions are identified with the single apex. So please fix the query there, then your change in snuba will be based on `Literals` not on `Columns`
Now since the existing snuba language is not really consistent with itself, what I just said does not apply to the conditions syntax `["timestamp", "<", "2020-01-01T00:00:00.000000Z"]` where the right hand side is assumed to be a literal. But for function calls the consideration above applies.

2) The time series processor. The fact that all entities are timeseries entities is a coincidence because we did not create the entities for CDC data (like groupedmessages and groupassignee). Those may not be such, so you should not rely on that processor if you want this to be a general change. Now is this change only supposed to apply to timeseries entities ?

**Comment by Zylphrex** [comment]
Thanks for clarifying. Since `["less", ["timestamp", "2020-01-01T00:00:00.000000Z"]]` should be an invalid expression in the snuba language, I don't think any change in snuba is actually necessary. This change was because I originally had thought that the conditions syntax `["timestamp", "<", "2020-01-01T00:00:00.000000Z"]` where the right hand side is assumed to be a literal should apply here and thus tried to convert the timeseries processor to handle that as well.

By adding the single apex to convert the expression to a literal, the existing timeseries processor already handles that use case. If there aren't any other concerns, I'll be closing this PR and making the necessary changes in sentry instead.

**Pull request closed without merging**
