### PR TITLE
ref(api): Removes deprecated routes

### PR DESCRIPTION
**Pull request by ahmedetefy**
Removes deprecated routes for creation and deletion of subscriptions that only accept dataset as url params, in favor of routes that take both a dataset and an entity key url params

Now that the routes called for subscriptions have been updated on sentry side, it makes sense to deprecate these 
https://github.com/getsentry/sentry/pull/30400
https://github.com/getsentry/sentry/pull/30432

### CODE REVIEW

**Review by evanh — COMMENTED** [review]
Question: are these endpoints completely gone in Sentry? Or are they being controlled by a feature flag?

**Comment by evanh** [comment]
Also please make sure the tests are all passing.

**Comment by ahmedetefy** [comment]
> Question: are these endpoints completely gone in Sentry? Or are they being controlled by a feature flag?

Completely gone

**Review by evanh — APPROVED** [review]
👍

**Review by lynnagara — APPROVED** [review]
Yay

**Pull request merged**
