### PR TITLE
fix(ast) Add missing ip_address conversion to translator.

### PR DESCRIPTION
**Pull request by fpacifici**
This translation was missing because I thought we would have the json ip serialization in the output by the time we got here. That way we would avoid doing the translation from ip address to string. This is still missing some parts (including a processing for conditions) so, in order to have feature parity with the legacy system we need to apply the same translation that happens here:
https://github.com/getsentry/snuba/blob/master/snuba/datasets/transactions.py#L131-L134

I was also thinking of putting these in the query processor. I cannot find a strong argument one way or another. This way the translated query is correct so we do not depend on query processors for correctness.

### CODE REVIEW

**Comment by lynnagara** [comment]
I'm a little bit surprised to see ip_address_v4 and ip_address_v6 fields still in the legacy implementation. i think `ip_address` is supposed to be the only publicly exposed field across events, transactions and discover. It seems it's not part of the Discover data model. I don't think anyone (i.e. Sentry) is aware of it and I wonder if we should take the opportunity to remove it instead so we don't get out of sync with Discover.

**Comment by fpacifici** [comment]
I'd love to remove those fields, I am not sure I am capable of answering your concern.
There is a test that leverages them
https://github.com/getsentry/snuba/blob/master/tests/test_transactions_api.py#L143-L165
@markstory @evanh do you know anything about this ? Can we just remove those fields from the transactions schema?

**Comment by lynnagara** [comment]
There is no reference to any "ip_address_v4" or "ip_address_v6" in the Sentry codebase which makes me think that Sentry developers don't know about it (nor should they since it's not supposed to be part of the model).

**Comment by markstory** [comment]
> There is no reference to any "ip_address_v4" or "ip_address_v6" in the Sentry codebase which makes me think that Sentry developers don't know about it (nor should they since it's not supposed to be part of the model).

We know its there but have not been using it as the `ip_address` field better suits our needs as it coalesces the v4 and v6 fields.

**Comment by evanh** [comment]
I think it's safe to remove. No one has that field in a saved query and we don't use it.

**Review by evanh — APPROVED** [review]

**Comment by lynnagara** [comment]
Could you remove the implementation from column_expr as well?

**Review by lynnagara — APPROVED** [review]

**Pull request merged**
