### PR TITLE
feat(migrations): Add the ability to update migration status

### PR DESCRIPTION
**Pull request by lynnagara**
Add a --fake option to `snuba migrations run` and `snuba migrations
reverse` commands, which updates the status of a migration without performing
the migration itself.

These won't be used under normal circumstances however it may be useful when:
- migrating from the old onto the new migration system
- keeping the migration table up to date after a migration is performed
manually

### CODE REVIEW

**Review by fpacifici — COMMENTED** [review]
I think we should have a different state other than `complete` for a migration that is completed through the `fake` approach, since we do not have any guarantee of the consistency of the schema.
So in that case if someone just ignore a migration and completes it with `fake`, and the issue shows up against later when they try to apply a migration that depends on the faked one we will be able to tell immediately the cause and we will not be looking into possible bugs.
Think about the bugs we ran into in the last few days, we know they are bugs because there was no migration system early on when we created the transactions table. The same kinds of issues may show up because someone faked a previous migration. At that point it will be very useful to separate legit bugs from issues due to improperly applied migrations.

**Comment by lynnagara** [comment]
I would prefer not to introduce new states here - I think it adds complexity that can't be reversed since it requires a new migration on the migrations table. I think the situation you described is reasonably unlikely to arise since:
- I assume you are mostly thinking of onpremise where people run things outside our control and we need to later debug, this is unlikely to come up in Sentry managed environments
- I don't really expect the `--fake` option to actually used and hence be the cause of problems itself (its mostly provided as an escape hatch in case something has gone wrong and we'd probably guide them through running this)
- If someone is altering their database directly (which shouldn't be done) we still don't have a way to detect it - whether they ran --fake or not is not actually the cause of the issue
- We have standardised the table schemas that everyone is running. Supporting multiple possible states isn't something I think we should worry about too much past this roll out

**Comment by fpacifici** [comment]
I am not referring to onpremise as the main use case. I am referring to internal cases where someone signals a there is an issue with migrations where snuba is not starting (like it happened this week due to bugs) and we won't be sure if the issue is due to them faking a migration before or whether it is a legit bug we need to fix. 

Why migrating the migration table is a concern?

**Comment by lynnagara** [comment]
It's obviously not difficult per se, it's just not temporary and hence I don't really want to do unless there's a real chance this actually arises. I can't actually imagine that happening right now. None of the bugs similar to this week would have been caught by a system like this since no one was (or will likely be) running the command with --fake. It's possible that people altered their database directly, but that's not actually something we can catch with this.

**Comment by fpacifici** [comment]
I think a case that would be hidden by this change actually happened. On monday Mark figured out that by forcing the status of the data migration on transactions the system would not get stuck there anymore. A few minutes later Alberto started asking why the following migration was not working (it was depending on the data migration). Had it not happened right away after people started forcing the state (thus making it obvious) it would have been a lot harder to debug why the data migration was marked as successful but the state was inconsistent. 

What about adding a separate column to flag faked migrations ? So the status is COMPLETE, none has to care about this additional state but we still have a trace of someone that is not guaranteed to have the database in a consistent state.

**Comment by lynnagara** [comment]
I'm confused about what you mean about those 2 users "forcing the state"? As far as I'm aware, they just ran the snuba in devservices, which runs the snuba devserver, which performs all migrations with the force flag. This caused a migration to fail since that had a previous db state that wasn't accounted for. No one went and altered anything directly nor would anything have been run with --fake even if this code was already merged. In that scenario, the other status would have been set anywhere.

**Review by fpacifici — APPROVED** [review]

**Pull request merged**
