### PR TITLE
Move stub subscription endpoints out of dev

### PR DESCRIPTION
**Pull request by wedamija**
Would be handy to have these endpoints available in prod so that my code that calls them doesn't fail.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
No issues with me.

**Comment by tkaemming** [comment]
My opinion: I'd like to not expose these in production until they're actually implemented, unless it's necessary.

**Comment by wedamija** [comment]
> My opinion: I'd like to not expose these in production until they're actually implemented, unless it's necessary.

What's the downside that you see? Atm these calls fail. I could just skip the calls, but in practice the response shouldn't change much once implemented.

**Comment by tkaemming** [comment]
I don't think there's much downside in this _specific_ case, and I do realize this is a slippery slope argument but I don't think making unimplemented features appear outwardly as implemented features is a habit that we should be getting into as a general rule.

I also don't know enough about your specific working situation to know why it's not enough to be able to test these endpoints in development. If the motivation here is that there is problem with the development environment not being representative of production, we should fix that. I understand that may not be practical now, but we should make it a priority to avoid things like this in the future.

I also don't know how much work on your end (I assume not much) to drop all of the data that was associated with subscriptions that appeared to be created but actually weren't whenever it's time to turn this on for real.

I'm not blocking it, though. I just don't think it's generally a good idea.

**Comment by wedamija** [comment]
> I don't think there's much downside in this _specific_ case, and I do realize this is a slippery slope argument but I don't think making unimplemented features appear outwardly as implemented features is a habit that we should be getting into as a general rule.
> 
> I also don't know enough about your specific working situation to know why it's not enough to be able to test these endpoints in development. If the motivation here is that there is problem with the development environment not being representative of production, we should fix that. I understand that may not be practical now, but we should make it a priority to avoid things like this in the future.

No, dev works fine, although it's reasonably slow. I mostly just want to be able to see this run in production and demo there rather than local.

> I also don't know how much work on your end (I assume not much) to drop all of the data that was associated with subscriptions that appeared to be created but actually weren't whenever it's time to turn this on for real.
> 
> I'm not blocking it, though. I just don't think it's generally a good idea.

It's not much work to remove this extra data. This time around I'd like to merge this, but I'll keep in mind for future Snuba related things to just mock until the endpoints are actually ready.

**Pull request merged**
