### PR TITLE
Revert "Add params for secure ClickHouse connections."

### PR DESCRIPTION
**Pull request by evanh**
Reverts getsentry/snuba#2018

### CODE REVIEW

**Review by fpacifici — APPROVED** [review]

**Comment by katsil** [comment]
Hi! Can you tell me why this issue reverted, i guess cliclhouse secure connection is very important issue

**Comment by katsil** [comment]
@fpacifici @evanh

**Comment by fpacifici** [comment]
Hi, sorry this was reverted because of a push safety issue with the original PR that caused a production issue when deployed.
The original PR is still desirable and should be fixed and re-issued. @evanh  did you have a chance to nail down the root cause ?

**Comment by katsil** [comment]
@evanh hi, im really waiting this feautre asap because we are trying to launch sentry 20 in production in destributed mode and DBaas databases (clickhouse) which supports only ssl/tls mode..

**Comment by evanh** [comment]
When we deployed this it caused Snuba to go into a crashloop and I haven't had time to spin up an environment to try and debug why. @katsil Did you test your changes outside of the tests included in Snuba?

**Comment by katsil** [comment]
@evanh i dont even tryed to run tests - just insert all changes inside snuba code, build docker image and push them to private registry, then got SSL CA CERT ERRORs.. 

Like:
```
2021-08-23 09:41:35,706 Failed to connect to my-ch-db-host:8443
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_driver/connection.py", line 260, in connect
    return self._init_connection(host, port)
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_driver/connection.py", line 226, in _init_connection
    self.socket = self._create_socket(host, port)
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_driver/connection.py", line 221, in _create_socket
    raise err
  File "/usr/local/lib/python3.8/dist-packages/clickhouse_driver/connection.py", line 212, in _create_socket
    sock.connect(sa)
  File "/usr/lib/python3.8/ssl.py", line 1342, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.8/ssl.py", line 1333, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)
```
```
clickhouse_driver.errors.NetworkError: Code: 210. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108) (sas-wfwqv2yebnxbtfrx.db.yandex.net:8443)
```

Can you tell me on which port i should connect - clickhouse own native port (9000/9440 for tls) or http/https clickhouse port (8123 or 8443 for https) *in my setup only 8443/9440 ports are available

**Comment by katsil** [comment]
@evanh hi, maybe any news? or we can reopen issue, i guess supporting clickhouse ssl is very important feature for snuba

**Comment by katsil** [comment]
@evanh If i run multiple snuba instances with multiple crons `gosu snuba snuba cleanup --storage transactions --dry-run False` is there any native snuba locks (if multiple cronjobs will run simultaneously?)

**Comment by konstantin-popov** [comment]
Hi @evanh, actually I successfully connected to ClickHouse using SSL. May be you can somehow debug the issue on your deploy?
@katsil, I guess your problem is in client-side cert validation error (disliking self-signed certificate), not server-side.

**Comment by evanh** [comment]
@konstantin-popov Sorry are you saying you tested your SSL change in Snuba and were able to successfully run tests with SSL enabled?

**Comment by konstantin-popov** [comment]
No, I didn't change testing environment to use SSL for ClickHouse connections (it would require some configuration effort to create certificates for CH and I thought it was not the thing worth testing).
What I meant is that I was able to start Snuba instances working with ClickHouse using SSL and it appears to function ok.
Is there a way I can help you in debugging the issue?

**Comment by patsevanton** [comment]
Has anyone had any luck connecting snuba to clickhouse over SSL? How did you do it (besides fixing the source code) ?

**Pull request merged**
