### PR TITLE
fix(snql) Allow arbitrary tags

### PR DESCRIPTION
**Pull request by evanh**
Tag names are arbitrary, so validating them is just going to end in failure.
Instead, create a special regex for tags that allows anything, and a separate
validator for all other subscriptables that should be more structured (e.g.
contexts).

### CODE REVIEW

**Comment by fpacifici** [comment]
I don't think we should allow arbitrary tags, imagine if we had a tag that starts with 16 black spaces followed by a bunch of unicode characters. While the ingestion is wrong when doing no sanitization, troubleshooting a query like that would be quite hard. 
Any reason why the current expression is not ok ? https://github.com/getsentry/snuba/blob/master/snuba/query/parser/__init__.py#L316

**Comment by evanh** [comment]
Does the current expression match what we allow? Why don't we allow unicode characters? What about slashes, semi-colons, @ signs? I'm happy to use the existing regex, I just don't want to have to keep going back and fixing corner cases. Also note that this isn't actually storing anything, it's just allowing people to query for them.

**Comment by fpacifici** [comment]
> Does the current expression match what we allow?
No. It is more restrictive. And the fact we allow that storage is the problem but it would be hard to change. 
I am not sure I understand why this is a SnQL bug though. Are we having queries that worked in the legacy language and not in SnQL? If yes, do you know why? As the legacy language itself has a tag validation regexp.

>  it's just allowing people to query for them.
My concern was about escaping these strings around (when we write to redis and send them to clickhouse). But I checked what we do there. We are fine.

**Comment by evanh** [comment]
> Are we having queries that worked in the legacy language and not in SnQL?

Yes the SnQL parser wasn't allowing `-` characters. When I went to fix that, it occurred to me that there might be a lot of other special characters we should allow as well. That's when I decided to add this looser regex specifically for tag keys.

**Review by fpacifici — APPROVED** [review]

**Comment by fpacifici** [comment]
ok

**Pull request merged**
