### PR TITLE
Bump Arroyo to 2.17.6

### PR DESCRIPTION
**Pull request by ayirr7**
Bumped the Python requirements, not sure if anything needs to be changed on the Rust side because of https://github.com/getsentry/snuba/blob/master/rust_snuba/Cargo.toml#L34

### CODE REVIEW

**Comment by untitaker** [comment]
you also need to run `cargo update -p`. also, you need to wait for getsentry/pypi to finish before CI can pass

**Review by onkar — COMMENTED** [review]
Did we do any testing to make sure that the new version works as expected? Please share the testing details in the PR.

**Comment by untitaker** [comment]
@onkar the changes in arroyo are not significant enough to cause concern like this. CI should be enough.

**Review by untitaker — APPROVED** [review]
thank you for your contribution!

**Pull request merged**
