### PR TITLE
fix(discover) Fix error caused by failure_rate()

### PR DESCRIPTION
**Pull request by evanh**
If failure_rate is used in an impossible function, the `transaction_status`
column will be changed to `NULL`. Clickhouse will error when presented with an
expression of the form `NULL IN (0, 1, 2)`. So change the function to instead be
chained AND to mitigate this.

### CODE REVIEW

**Comment by lynnagara** [comment]
I'm probably lacking some context here, but I assume this happens when the selected table is events, and we are asking for the failure rate on that, which is invalid since there won't be any transaction status there. I wonder if we should just return null for entire failure_rate expression on that table since it shouldn't be valid instead of trying to transform parts of it.

**Comment by evanh** [comment]
You're absolutely right about when this happens, it's when someone has failure_rate in the query and also selected the events table.

As for NULLing the entire expression, I have a PR open to handle some cases like that https://github.com/getsentry/snuba/pull/1383. I'm not sure how to make the change you're suggesting. Where would that transformation happen?

**Comment by lynnagara** [comment]
A few options where we might do a transformation like this:
1 - have the list of query processors depend on which entity/storage is picked in the discover dataset, if we picked transactions include the failure rate processor, otherwise omit it (and possibly replace it with a null processor).
2- Move part of query processing responsibility to the entity, the failure rate processor only happens if transaction entity is picked, the errors entity does the null transformation if it encounters such an expression
3 - Since the failure rate processor is passed the data model just return null if the transaction_status column is missing

**Comment by fpacifici** [comment]
Regarding option 1: I don't think we should change the Snuba architecture (which calls for the logical query processing to be independent from the storages we pick) to accommodate for impossible queries. Such change will happen automatically when entities will be picked earlier in the flow, but it will be a long time before discover fully relies on this model. Making the processor depend on the result of the storage choice in the current architecture would introduce a circular dependency that will generate unexpected results (the translator depends on the results of processors).

Regarding option 2: We are still working on the default entity, so that may be the option later.

Not following option 3. This processor happens before we know if the transaction_status column exists. 

More in general, when entities will be picked when sending the query this should not be a problem.

**Comment by evanh** [comment]
We could add a translator to handle these cases. E.g. have a translator in the event storage that looked for the failure_rate expression, and converted it to NULL. That should be in a separate PR though.

**Comment by fpacifici** [comment]
Ok with that. @lynnagara how does it sound ?

**Comment by lynnagara** [comment]
That works for me

**Review by lynnagara — APPROVED** [review]

**Pull request merged**
