### PR TITLE
feat(replays): Add error and session sample rate columns

### PR DESCRIPTION
**Pull request by cmanallen**
closes: https://github.com/getsentry/replay-backend/issues/226

### CODE REVIEW

**Comment by evanh** [comment]
Was there a migration for these columns? I think that's why the CI is failing.

**Comment by cmanallen** [comment]
@evanh Yes its here: https://github.com/getsentry/snuba/pull/3587.  There's two open questions if you don't mind taking a peek.

**Review by evanh — APPROVED** [review]
OK. Assuming the CI all passes this looks good to me.

**Comment by cmanallen** [comment]
@evanh Are you able to approve this codecov regression?

**Pull request merged**
