### PR TITLE
build: Bump clickhouse-driver to 0.1.5

### PR DESCRIPTION
**Pull request by lynnagara**

### CODE REVIEW

**Review by evanh — APPROVED** [review]
I hope it's this easy. Is there a way to canary this against prod before deploying?

**Comment by fpacifici** [comment]
First we need to look into the release notes of this version and the previous ones we skipped. This is to find anything suspicious.
Then we need to run all sentry tests
Then if we want to canary we can ask the ops team if they have a good way to doo this on a one off base. Setting up canary deployment by default is something we can and should do but not trivial

**Comment by lynnagara** [comment]
I couldn't spot anything in the changelog that looked suspicious. It a change in the patch version that looks to contain only bug fixes, performance improvements and additional functionality that is backwards compatible. I ran the Sentry tests against this and everything looks fine, but I'm not sure how to (at least easily) test this in production without fully rolling out the change, or if that's something we should try and prioritise here.

**Comment by evanh** [comment]
I pulled the branch and tested myself locally. Everything works for me so my earlier troubles must have been fixed by your changes.

**Comment by fpacifici** [comment]
Read through the changelog. This is fine and the change is small enough not to require a special canary.
Let's just do a test on the distributed table as we discussed yesterday before merging.

**Pull request merged**
