### PR TITLE
fix(project extension) Avoid unnecessary conditions

### PR DESCRIPTION
**Pull request by evanh**
If the user is filtering to a specific project, there's no need to add a
potentially huge extra condition.

### CODE REVIEW

**Comment by fpacifici** [comment]
Thanks for doing this. Could you be more specific on which cases are we dealing with here? Why is the query passing the project id as a condition instead of using the extension and what is the reasoning for prioritizing the project filter on the query instead of prioritizing the one in the extension?

**Comment by evanh** [comment]
On the Sentry side, there are two different ways for the project to get passed through: through the project selections in the global header, or by the user manually applying a filter in the discover query. Those get passed through separately, as the "project" environment and an explicit condition respectively.

I have another PR open in Sentry to limit passing through the environment if the user has added an explicit project condition, but I thought this check should exist as well just in case.

**Comment by fpacifici** [comment]
I still don't get why we decided to give priority to the condition clause with regards to the extension.  We should not have queries with both a project extension and a project condition to begin with since the extension is mandatory.
- what was the downside of having the two conditions ?
- why we pick the project condition from the condition field over the one in the extension? This feels pretty arbitrary to solve a product problem. In reality the client should never pass a project condition in the condition clause and use the extension instead (unless there is a complex OR, which would require both), since the extension is required.
- why does this not take into account conditions like project_id IN (1,2,3,) ?

**Comment by evanh** [comment]
OK. I already made a change on the product side to try and avoid sending unnecessary project IDs so I'll just close this.

**Pull request closed without merging**
