### PR TITLE
On Freight deploy, update k8s deployments containing `events-subscriptions-executor` container

### PR DESCRIPTION
**Pull request by oioki**
Similar to https://github.com/getsentry/snuba/pull/2278 https://github.com/getsentry/snuba/pull/2249

### CODE REVIEW

**Review by evanh — APPROVED** [review]
This is fine, but as Filippo mentioned in Slack this isn't used in prod yet.

**Comment by fpacifici** [comment]
The executor is in a crash loop now, I believe it is because it fails to commit on kafka and we went out of retention. 
If we merge this it will prevent us from deploying. So let's keep it open so it is not redeployed and I will find some time to clean it up this week.

**Review by fpacifici — CHANGES_REQUESTED** [review]
See comment above. Let's not merge this until the executor is fixed.

**Comment by lynnagara** [comment]
Sorry, I didn't see this PR earlier before making a duplicate. Closing because it's been added in https://github.com/getsentry/snuba/pull/2350

**Pull request closed without merging**
