### PR TITLE
fix: Enable pre-commit CI check

### PR DESCRIPTION
**Pull request by asottile-sentry**
commits are split into atomic tasks -- it's recommended to view the reformat commits with [?w=1](https://youtu.be/qYJWBJvHqj0)

___

previously the check in CI was always silently passing due to `master` not being
available with `actions/checkout@v2`:

```
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### CODE REVIEW

**Review by asottile-sentry — COMMENTED** [review]
I read through the automated patches and commented on the surprises

**Comment by evanh** [comment]
I'm a little confused, what is the actual change here? Even ignoring whitespace this PR is >2000 lines long. Are all the reformatting changes because of a new version of a linter? If so, can you configure black to not make all these changes?

**Comment by asottile-sentry** [comment]
> I'm a little confused, what is the actual change here? Even ignoring whitespace this PR is >2000 lines long. Are all the reformatting changes because of a new version of a linter? If so, can you configure black to not make all these changes?

the linters are "configured" but aren't being enforced in CI -- this PR fixes them to be enforced in CI (the fourth commit) and resolves the drift from un-linted/un-formatted changes (second and third commits) which have been introduced due to the CI check erroneously passing.

**Comment by evanh** [comment]
OK I understand what is being changed.

> which have been introduced due to the CI check erroneously passing.

The pre-commit linters were still happening locally though. My suggestion here would be to fix the CI check, but don't lint the entire code base. The files that are currently not linted correctly will get fixed if/when they get changed in subsequent PRs.

**Comment by asottile-sentry** [comment]
> OK I understand what is being changed.
> 
> > which have been introduced due to the CI check erroneously passing.
> 
> The pre-commit linters were still happening locally though. My suggestion here would be to fix the CI check, but don't lint the entire code base. The files that are currently not linted correctly will get fixed if/when they get changed in subsequent PRs.

they were happening when people used them, but as far as I can tell they weren't running in the general case (`black` for instance in its current configuration cannot run successfully at all!  the version configured always crashes with the common `_unicodefun` error: https://github.com/psf/black/issues/2964)

generally I [recommend doing it all in one PR](https://github.com/readme/guides/code-review) otherwise other PRs will end up with unrelated linter/formatter noise which makes it more difficult to accurately review changes being made.  I specifically separated the noisy commits into separately reviewable patches for this reason

**Review by evanh — APPROVED** [review]
I meant to say, I think this would have been working when it was run as part of the pre-commit locally on `git commit`. However this is fine, I'll approve before you get more merge conflicts.

**Pull request merged**
