### PR TITLE
Add kafka ssl authentication params to snuba

### PR DESCRIPTION
**Pull request by bumarcell**
### Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

### CODE REVIEW

**Comment by onewland** [comment]
Hi @bumarcell,

Thanks for your PR.

If you'd like to add these options to your local environment, you can do that without this change. You can create a new file in the settings/ directory that overrides the values in `settings/__init__.py` and run snuba with `SNUBA_SETTINGS=your_env_name`. The makefile does this for `make test` (`SNUBA_SETTINGS=test`).

Your comment fix is an improvement if you're interested in contributing just that.

**Comment by bumarcell** [comment]
Hello @onewland 
Thanks for your response! 

So my goal is to deploy sentry (with snuba) in k8s through the helm chart (v15).
The workaround you suggested still needs me to clone snuba and build it locally, which what I already did up till this point.
Ideally I'd like to be able to use sentry and Snuba from your source (with updates possible) while being able to use external Kafka with ssl auth and without having to build Snuba myself every time I need to get an update :) 

P.S. Unfortunately at the moment when I try to use latest Snuba 22.7.0 the deployment fails at `snuba-migration-job` - apparently because Snuba tries to migrate some field called GENERIC_METRICS_.. which internal Clickhouse doesn't recognize and breaks the whole thing..

**Comment by onewland** [comment]
re: the migration, that's a separate issue that I think is worth filing at https://github.com/getsentry/snuba/issues

We'll discuss internally about whether we think it's a good idea to add this environment-based control for Kafka connection settings.

**Comment by onewland** [comment]
I think we're fine with this change in principle. Letting the CI run go and if that passes we need to make sure it doesn't conflict with our production settings.

**Review by onewland — APPROVED** [review]

**Pull request merged**
