### PR TITLE
fix(rpc): Correct config key for rpc endpoints

### PR DESCRIPTION
**Pull request by Zylphrex**
The config key should be based on the protobuf classes instead of the endpoint.

### CODE REVIEW

**Comment by volokluev** [comment]
@Zylphrex 

How strongly do you feel that this should be the case? I'm not super attached to it but also don't necessarily feel like updating all the tests. The naming convention follows the `endpoint_*` file naming conventions stated [here](https://github.com/getsentry/sentry-protos/blob/main/proto/sentry_protos/snuba/README.md#conventions)

**Comment by Zylphrex** [comment]
> @Zylphrex
> 
> How strongly do you feel that this should be the case? I'm not super attached to it but also don't necessarily feel like updating all the tests. The current naming convention follows the `endpoint_*` file naming conventions stated [here](https://github.com/getsentry/sentry-protos/blob/main/proto/sentry_protos/snuba/README.md#conventions)

I'm not attached to it but the names of the classes are now public interface as it determines the endpoint. So if we were to use the class names in snuba to decide the endpoint paths, we now have to
1. ensure they do not change
2. we now need to hard code a mapping from the rpc name to the snuba class name within the sentry code base for every rpc call as we can not rely on the rpc class to tell us which endpoint it needs to call

**Comment by volokluev** [comment]
> we now need to hard code a mapping from the rpc name to the snuba class name within the sentry code base for every rpc call as we can not rely on the rpc class to tell us which endpoint it needs to call

@Zylphrex I see what you're saying. Here is what I will say. In gRPC, the definition of the RPC and request/response payload are separate ([example](https://grpc.io/docs/what-is-grpc/core-concepts/#service-definition)) because they are separate things. When we switch to gRPC you'd have to do this anyways. What you are proposing would make that transition more difficult

**Comment by Zylphrex** [comment]
Closing this in favour of helper functions in sentry that maps to each rpc endpoint

**Pull request closed without merging**
