### PR TITLE
fix(tiger): don't call the explicit tuple function in clickhouse

### PR DESCRIPTION
**Pull request by volokluev**
After drilling down enough, it seems like this is actually the cause of the bugs. I thought I tried it a week ago when @evanh told me to but I guess I didn't try it correctly. Either way this should actually fix the problems. It looks like we already had to implement a similar fix for arrays so this should be no different.

### CODE REVIEW

**Review by nikhars — APPROVED** [review]

**Comment by nikhars** [comment]
Is there a way to enforce this only on tiger queries? I think the answer is No. But would it make sense to try and restrict this only to tiger queries?

**Comment by volokluev** [comment]
Is it possible? Yes. Is it easily possible without dirty hacks? no

Does it make sense?

it makes sense-ish. This change would affect every query but there's no reason it shouldn't work I can hide it behind a runtime flag so we can turn it on slowly if that makes you feel more comfortable

**Comment by volokluev** [comment]
I'm also not going to deploy this on a friday afternoon. I'll wait till monday

**Comment by nikhars** [comment]
> Is it possible? Yes. Is it easily possible without dirty hacks? no
> 
> Does it make sense?
> 
> it makes sense-ish. This change would affect every query but there's no reason it shouldn't work I can hide it behind a runtime flag so we can turn it on slowly if that makes you feel more comfortable

The change seems relatively straightforward so I am fine to run this without the runtime flag.

**Comment by nikhars** [comment]
> I'm also not going to deploy this on a friday afternoon. I'll wait till monday

I would probably try this out on a Friday than on Monday because of low traffic volumes. On Monday we run the weekly reports so we are running more queries. Just my opinion. You are free to decide when you want to try it out.

**Pull request merged**
