### PR TITLE
ref(query): Use result cache in testing

### PR DESCRIPTION
**Pull request by tkaemming**
See #805. If applied on ec59f9c instead of 111b04d, this causes the tests to fail.

### CODE REVIEW

**Comment by tkaemming** [comment]
I'd prefer that this would just exercise the encoding/decoding aspects of the cache without the state, but that'd be a more invasive change that I don't care to make right now.

**Review by fpacifici — APPROVED** [review]
Any reason for not enabling RECORD_QUERIES as well? It carries the same risk.

**Comment by tkaemming** [comment]
> Any reason for not enabling RECORD_QUERIES as well? It carries the same risk.

It is [wrapped in a large `try`/`except` block](https://github.com/getsentry/snuba/blob/b154aabd5093daa3c7f568645a9ac7b501c9f227/snuba/state/__init__.py#L228-L244), so failures there won't prevent the response from being returned (and unfortunately won't fail the tests either, so we won't realize it's broken until somebody looks for data that isn't there.)

**Comment by tkaemming** [comment]
> > Any reason for not enabling RECORD_QUERIES as well? It carries the same risk.
> 
> It is [wrapped in a large `try`/`except` block](https://github.com/getsentry/snuba/blob/b154aabd5093daa3c7f568645a9ac7b501c9f227/snuba/state/__init__.py#L228-L244), so failures there won't prevent the response from being returned (and unfortunately won't fail the tests either, so we won't realize it's broken until somebody looks for data that isn't there.)

On second thought, I am going to turn this on in the test settings in case this behavior inadvertently changes at a later date in a way that would cause problems. Whether it does or doesn't right now doesn't really matter.

**Pull request merged**
