### PR TITLE
Demote `device_family` column.

### PR DESCRIPTION
**Pull request by JTCunning**

### CODE REVIEW

**Comment by fpacifici** [comment]
Do these tests pass (they do not run in CI )?
https://github.com/getsentry/snuba#testing-against-sentry

**Comment by JTCunning** [comment]
My workstation is fucked up when it comes to compiling the clickhouse driver. I just threw this up so travis could do it.

**Comment by fpacifici** [comment]
I get one failure. Will check the details later:

```
__________________________________________________ OrganizationEventsV2EndpointTest.test_event_and_user_counts ___________________________________________________
Traceback (most recent call last):
  File "/Users/filippopacifici/sentry/tests/snuba/api/endpoints/test_organization_events_v2.py", line 256, in test_event_and_user_counts
    assert response.data[0]['issue.id'] == groups[0].id
AssertionError: assert 92 == 93
 +  where 93 = <Group at 0x113fbe090: id=93, project_id=146>.id
---------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------
18:48:22 [INFO] sentry.superuser: superuser.logged-in (user_id=111 ip_address=u'127.0.0.1')
----------------------------------------------------------------------- Captured log call ------------------------------------------------------------------------
superuser.py               288 INFO     superuser.logged-in
------------------------------------------ generated xml file: /Users/filippopacifici/sentry/.artifacts/snuba.junit.xml ------------------------------------------

---------- coverage: platform darwin, python 2.7.16-final-0 ----------
Coverage XML written to file .artifacts/snuba.coverage.xml

================================================== 1 failed, 328 passed, 5 xfailed, 2 xpassed in 170.05 seconds ==================================================
```

**Comment by fpacifici** [comment]
The events table is no more.

**Pull request closed without merging**
