### PR TITLE
fix(rust): Fix `self.consumer_offsets`

### PR DESCRIPTION
**Pull request by lynnagara**
self.consumer_offsets is the latest offsets seen by the consumer, not the committed offsets.

### CODE REVIEW

**Review by untitaker — APPROVED** [review]
ugh, sorry about that. I recently added this, i can't remember what I thought there. I was somehow under the impression that I ported `self.__offsets` from python, but indeed it's read offsets.

**Comment by lynnagara** [comment]
@untitaker Check out the failing test now?! Isn't that the offset reset error we actually saw in prod?

**Comment by untitaker** [comment]
> @untitaker Check out the failing test now?! Isn't that the offset reset error we actually saw in prod?

the error is fine. we currently log errors even though we then later reset the offset. the logged error is normal. the test is failing because of the next few lines, where `consumer.tell()` is returning the wrong value. and I think it's because i misunderstood what it's for

**Comment by lynnagara** [comment]
> the error is fine. we currently log errors even though we then later reset the offset. the logged error is normal. the test is failing because of the next few lines, where `consumer.tell()` is returning the wrong value. and I think it's because i misunderstood what it's for

ah you're right, didn't read error message properly

**Pull request merged**
