### PR TITLE
fix(caching) Turn off query caches in test and dev

### PR DESCRIPTION
**Pull request by evanh**
The idea is to disable the query caches when running tests or running snuba
locally.

### CODE REVIEW

**Comment by fpacifici** [comment]
Why should we remove caching during tests across the board on test_api? Do we have specific issues we are running into?
If we remove it we would loose a lot of coverage on a fundamental code path that runs in production. It already happened (at a time cache was disabled locally) to cause a production incident for breaking the serialization logic without noticing on the tests environment.

**Comment by evanh** [comment]
Maybe we need a flag then? Dan is struggling to test the changes here https://github.com/getsentry/sentry/pull/24231 because Snuba is caching things. I'm not sure of the best way to help him.

**Comment by evanh** [comment]
@wedamija Can you clarify why this is necessary?

**Comment by wedamija** [comment]
> @wedamija Can you clarify why this is necessary?

Basically in a forthcoming PR I'm making identical queries, but inserting events in between runs which should change the results. I didn't realise the cache was running in tests, and I spent a while confused about the behaviour that I was seeing until I realised what was happening.

Is it possible to just disable the cache in `sentry devservices` and keep it going for snuba tests themselves? Would that be enough to keep the path tested?

**Comment by evanh** [comment]
> Alternatively, I'd be fine with passing a param to disable the caching.

There is actually a /config endpoint on Snuba where you can override settings like the ones in this PR. https://github.com/getsentry/snuba/blob/master/snuba/web/views.py#L255

Might be a workaround for now, I don't want this to block getting the cache out.

**Comment by wedamija** [comment]
> > Alternatively, I'd be fine with passing a param to disable the caching.
> 
> There is actually a /config endpoint on Snuba where you can override settings like the ones in this PR. https://github.com/getsentry/snuba/blob/master/snuba/web/views.py#L255
> 
> Might be a workaround for now, I don't want this to block getting the cache out.

I don't think I'm blocked, but the tests will be more accurate if I can disable. I'll put up a separate pr to hit this endpoint and disable this setting during tests.

**Comment by fpacifici** [comment]
> Is it possible to just disable the cache in sentry devservices 

I don't think we should switch the default behavior developers would have to something that does not match production in order to fix one test. The caching behavior is important for developers using devservices as that is the production behavior.
It seems that the wrong perception around how caching work is what should be fixed.


I think disabling the cache during the specific test and enabling it afterwards would be a better option. We could even allow a `no-cache` parameter in the query payload as a setting.

**Comment by wedamija** [comment]
> > Is it possible to just disable the cache in sentry devservices
> 
> I don't think we should switch the default behavior developers would have to something that does not match production in order to fix one test. The caching behavior is important for developers using devservices as that is the production behavior.
> It seems that the wrong perception around how caching work is what should be fixed.
> 
> I think disabling the cache during the specific test and enabling it afterwards would be a better option. We could even allow a `no-cache` parameter in the query payload as a setting.

I'm ok with a `no-cache` parameter. But I'm not sure we've thought out the cache behaviour thoroughly for tests - do we reset the snuba cache after every test, for example? It may not matter if we're always changing params, but this just feels like something people are going to stumble over and be confused about, like I was.

One thing that could be helpful is to return whether a given response is cached, either as part of the returned data or included in the headers, that way at least I could look at the response and understand what's going on. We could potentially use this to inform our own caching a little better, if it had info on when the cache would expire.

**Comment by fpacifici** [comment]
> do we reset the snuba cache after every test, for example?
We are supposed to. Redis is flushed when we  truncate the dataset.

> One thing that could be helpful is to return whether a given response is cached,
This is already the case. The `stats` field the client receives in debug mode contains a `cache_hit` field.

**Comment by evanh** [comment]
I'll add a story to add the "no-cache" parameter and return a flag in the response if the cache was used or not.

**Comment by wedamija** [comment]
> I'll add a story to add the "no-cache" parameter.

JYFI, at the moment I'm using
```
    @contextmanager
    def disable_snuba_query_cache(self):
        self.snuba_update_config({"use_readthrough_query_cache": 0, "use_cache": 0})
        yield
        self.snuba_update_config({"use_readthrough_query_cache": None, "use_cache": None})

    def snuba_update_config(cls, config_vals):
        return _snuba_pool.request("POST", "/config.json", body=json.dumps(config_vals))
```
to handle this. It might be good enough for our needs, maybe easier to use than a query param, since I don't need to pass it all the way through the stack.

**Comment by evanh** [comment]
I'm going to close this PR, since we have an Asana task to track the no-cache parameter story and Sentry has a decent workaround for the problem as it exists now.

**Pull request closed without merging**
