### PR TITLE
perf(replacers): Adjust the dimension of tag deletion to be in PREWHERE and not WHERE clause.

### PR DESCRIPTION
**Pull request by JTCunning**
Before: `1.21 million rows/s`
After: `5.35 million rows/s`

### CODE REVIEW

**Comment by JTCunning** [comment]
This is now ready.

**Review by tkaemming — APPROVED** [review]
Way out of scope for this but it'd be nice if this eventually went through general query processing for consistency.

**Comment by fpacifici** [comment]
@tkaemming  we cannot do that for the entire query, the replacement query are very not supported by the snuba query language or structure since they are all `INSERT INTO ... SELECT ......`.
We can express as snuba query the select part of that, though.

**Comment by tkaemming** [comment]
> @tkaemming we cannot do that for the entire query, the replacement query are very not supported by the snuba query language or structure since they are all `INSERT INTO ... SELECT ......`.
> We can express as snuba query the select part of that, though.

Yes, that's why I said "eventually".

**Pull request merged**
