### PR TITLE
feat(measurements) Arrayjoin optimizer for measurements

### PR DESCRIPTION
**Pull request by fpacifici**
Depends on https://github.com/getsentry/snuba/pull/1244

When we use arrayJoin on tags we need to do some additional processing on those collumns:
- if we are arrayJoining on both key and value, we must arrayJoin on the pairs and not do that inndependently. `arrayJoin(arrayMap(key, val -> (key, val), tags.key, tags.value)` otherwise we would obtain the cartesian product of the two columns.
- we optimize fitlering over the arrayJoin by doing an arrayFilter before the arrayJoin to reduce the result size.

This applies such processing to measurements.

### CODE REVIEW

**Comment by fpacifici** [comment]
Design is on hold. Converting to draft.

**Comment by fpacifici** [comment]
Resurrecting this since the project is moving again

**Review by evanh — APPROVED** [review]
It would be nice to add an API test that has a measurement in an arrayjoin.

**Comment by fpacifici** [comment]
Now this depends on https://github.com/getsentry/snuba/pull/1334 which allows the support for multiple arrayJoin columns.
That check did not exist when this PR was first built.

**Pull request merged**
