### PR TITLE
fix(replays): add uuid processor to replay_id column

### PR DESCRIPTION
**Pull request by JoshFerge**
This will make it so replay_ids dashes are stripped, akin to how our other uuid field dashes are stripped.

### CODE REVIEW

**Comment by volokluev** [comment]
Is there anyone using the replay id in queries at the moment that this would break?

**Comment by JoshFerge** [comment]
@volokluev  no. this field isn't available to be queried through any of our APIs yet.

**Review by volokluev — APPROVED** [review]

**Comment by mcannizz** [comment]
@JoshFerge this PR has been open for a long time. Do you still want to make this change or should we close it?

**Comment by JoshFerge** [comment]
can go ahead and close it, thanks. I don't know that this would have done much perf wise..

**Pull request closed without merging**
