### PR TITLE
feat(replays): Set platform as empty string if platform is not provided

### PR DESCRIPTION
**Pull request by cmanallen**
Previously it was set to `javascript` as that was the only platform replay was available on.  With the addition of mobile replays this is no longer true.  The query in `sentry` already uses the `anyIf` operator and filters out empty values.

Related: https://github.com/getsentry/sentry/issues/74074

### CODE REVIEW

**Comment by michellewzhang** [comment]
does this mean that if someone were to refresh the page on a mobile replay (referencing the video @romtsn sent), the platform in the tags panel might sometimes disappear (instead of changing to javascript)?

**Comment by cmanallen** [comment]
@michellewzhang No if a non-empty value is set it will always be returned.  There should only be one non-empty value.  If there are two (in the case @romtsn identified) then one of the non-empty values will be chosen at "random".

**Review by michellewzhang — APPROVED** [review]

**Review by ayirr7 — APPROVED** [review]
Might also be a good idea to update any schema examples in the sentry-kafka-schemas repo if needed.

**Comment by cmanallen** [comment]
@ayirr7 All good.  Platform is not provided on any of the affected events.

**Pull request merged**
