### PR TITLE
feat(eap-api): Use signs in count, average, and sum calculations

### PR DESCRIPTION
**Pull request by davidtsuk**
Closes https://github.com/getsentry/eap-planning/issues/105

### CODE REVIEW

**Review by volokluev — APPROVED** [review]

**Comment by kylemumma** [comment]
What is the motivation behind this PR?

**Comment by davidtsuk** [comment]
> What is the motivation behind this PR?

We are using a ReplacingMergeTree which stores a sign representing whether a row was added or deleted. In order to compute counts, sums, and averages correctly we need to account for the sign in the calculation.

**Comment by onkar** [comment]
@davidtsuk should we add unit tests covering the sign representation?

**Comment by davidtsuk** [comment]
> @davidtsuk should we add unit tests covering the sign representation?

We aren't actually using negative signs yet, so we can't add any tests yet for that. Since the existing tests pass, I think it's okay to wait until we start using negative signs.

**Pull request merged**
