### PR TITLE
feat(replays): Add low cardinality encoding to select columns

### PR DESCRIPTION
**Pull request by cmanallen**
Its not expected that any column listed in the migration will ever exceed 100k unique values.  Encoding them with the low cardinality codec will significantly improve most operations on these columns.

Edit: the tests seem to fail no matter what I do?  `test_no_schema_differences` fails if I don't update the replays.yaml.  If I do update the replays.yaml then `ddl-changes / Post new DDL changes from migrations (pull_request)` fails.  Any advice would be appreciated.

### CODE REVIEW

**Comment by evanh** [comment]
> will significantly improve most operations on these columns.

Do you have these numbers somewhere?

**Comment by cmanallen** [comment]
@evanh Unfortunately ephemeral.  However, I can easily reproduce these numbers for you.  I have some tools which make performance testing easier.  I will update this pull and the others tomorrow with performance data (along with my testing methodology so you can sanity check me).

**Comment by cmanallen** [comment]
@evanh @nikhars Benchmarking results.

# String Encodings

Test Table:

```sql
CREATE TABLE default.replays_test
(
    `project_id` UInt64,
    `timestamp` DateTime,
    `replay_id` UUID,
    `segment_id` UInt32,
    `browser_null` Nullable(String),
    `browser_nn` String,
    `browser_nn_lc` LowCardinality(String),
    `browser_nn_lc_cmp` LowCardinality(String) CODEC(ZSTD)
)
ENGINE = ReplacingMergeTree
ORDER BY (project_id, timestamp, replay_id, segment_id)
```

Tested on 1 million row data set.

Legend:

- "nn" Not Null
- "nn_lc" Not Null, Low Cardinality
- "nn_lc_zstd" Not Null, Low Cardinality, ZSTD

**Random distribution is the expected production ordering for these values.**

**Partially ordered means a run of 10 identical browser names before changing browser.**

```
┌─name────────────────compressed_size───uncompressed_size─────ratio─┐
│ PARTIALLY ORDERED DISTRIBUTION - NO NULL OR EMPTY                 │
│───────────────────────────────────────────────────────────────────│
│ browser_null       │ 372.10 KiB      │ 9.68 MiB          │  26.63 │
│ browser_nn         │ 367.72 KiB      │ 8.72 MiB          │  24.29 │
│ browser_nn_lc      │ 270.60 KiB      │ 978.56 KiB        │   3.62 │
│ browser_nn_lc_zstd │ 120.47 KiB      │ 978.56 KiB        │   8.12 │
│────────────────────┴─────────────────┴───────────────────┴────────│
│ PARTIALLY ORDERED DISTRIBUTION - 50/50 NULL OR EMPTY              │
│───────────────────────────────────────────────────────────────────│
│ browser_null       │ 1.71 MiB        │ 5.79 MiB          │   3.38 │
│ browser_nn         │ 1.14 MiB        │ 4.84 MiB          │   4.24 │
│ browser_nn_lc      │ 525.18 KiB      │ 978.56 KiB        │   1.86 │
│ browser_nn_lc_zstd │ 286.81 KiB      │ 978.56 KiB        │   3.41 │
│────────────────────┴─────────────────┴───────────────────┴────────│
│ RANDOM DISTRIBUTION - NO NULL OR EMPTY                            │
│───────────────────────────────────────────────────────────────────│
│ browser_null       │ 2.53 MiB        │ 9.67 MiB          │   3.82 │
│ browser_nn         │ 2.53 MiB        │ 8.72 MiB          │   3.45 │
│ browser_nn_lc      │ 738.31 KiB      │ 978.56 KiB        │   1.33 │
│ browser_nn_lc_zstd │ 379.48 KiB      │ 978.56 KiB        │   2.58 │
│────────────────────┴─────────────────┴───────────────────┴────────│
│ RANDOM DISTRIBUTION - 50/50 NULL OR EMPTY                         │
│───────────────────────────────────────────────────────────────────│
│ browser_null       │ 2.01 MiB        │ 5.75 MiB          │   2.87 │
│ browser_nn         │ 1.43 MiB        │ 4.80 MiB          │   3.35 │
│ browser_nn_lc      │ 625.70 KiB      │ 978.56 KiB        │   1.56 │
│ browser_nn_lc_zstd │ 359.72 KiB      │ 978.56 KiB        │   2.72 │
└────────────────────┴─────────────────┴───────────────────┴────────┘
```

Query Performance:

```
┌─memory_usage─┬─query_duration_ms─┬─query──────────────────────────────────────────────────────────────────────────────────────────────────────┐
│     21358422 │                25 │ SELECT replay_id FROM replays_test GROUP BY replay_id HAVING sum(browser_null = 'Safari') > 0 LIMIT 1      │
│     17449545 │                21 │ SELECT replay_id FROM replays_test GROUP BY replay_id HAVING sum(browser_nn = 'Safari') > 0 LIMIT 1        │
│     22812555 │                12 │ SELECT replay_id FROM replays_test GROUP BY replay_id HAVING sum(browser_nn_lc = 'Safari') > 0 LIMIT 1     │
│     22119911 │                12 │ SELECT replay_id FROM replays_test GROUP BY replay_id HAVING sum(browser_nn_lc_cmp = 'Safari') > 0 LIMIT 1 │
└──────────────┴───────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Review by evanh — COMMENTED** [review]
Thanks for this! Interesting findings. I am trying to figure out how to best get these changes out.

I think if you can get the rest of CI passing, we can bypass the DDL check in this case.

**Comment by cmanallen** [comment]
@evanh  Done 👍

**Pull request merged**
