### PR TITLE
feat(clickhouse): allow configuring clickhouse database

### LINKED ISSUE #874: Add ability to change Clickhouse database name
Currently, the database name in connection isn't set, so `clickhouse_driver` uses `default` database name, and we can't change it via env variables. But the CLI scripts (like `cleanup`, `migration`, etc.) have the `database` option, where we can set it up.

That would be great if the database name option will be added to the env variables.

We`re using Sentry on-premise with external Clickhouse installation, where we store some other applications data, so the `default` database name is confusing.

### PR DESCRIPTION
**Pull request by chhetripradeep**
Closes https://github.com/getsentry/snuba/issues/874

This PR adds a database variable to the clickhouse connection hence all further read, write clickhouse operations will happen to the tables in this database. I have tested with my development sentry10 setup.

### CODE REVIEW

**Comment by lynnagara** [comment]
Thanks @chhetripradeep I think this will be a really useful feature. I believe that we will also need to update the errors replacer. (https://github.com/getsentry/snuba/blob/master/snuba/datasets/errors_replacer.py). 

We should see if we can easily run our tests with a non default database name to help catch any other cases like this.

**Comment by chhetripradeep** [comment]
Thank you @lynnagara for reviewing the PR. Since i am not much familiar with the codebase, i am not sure which all changes i need to make in errors replacer and how can i test those changes. It'll be very helpful if you can suggest me those.

**Comment by lynnagara** [comment]
Sorry @chhetripradeep I think I was wrong earlier. I thought that the `insert_query_template` and `count_query_template` also needed to have the db prefix on the table name. But it's seems thats not necessary since database is already a property of the ClickHouse connection. So this looks good to me. Just needs updated with master.

**Comment by chhetripradeep** [comment]
Thank you so much @lynnagara for your constant help in the PRs, much appreciated. I have updated this PR too rebasing it with master.

**Review by lynnagara — APPROVED** [review]
Thanks

**Pull request merged**
