### PR TITLE
feat(replays): Add encodings to numeric columns

### PR DESCRIPTION
**Pull request by cmanallen**
Edit: tests fail because storages/replays.yaml.  If I update it the `ddl-changes / Post new DDL changes from migrations (pull_request)` check will fail.

All values are LZ4 compressed rather than ZSTD.  ZSTD has better compression but I know its slightly slower.  I wasn't sure how to measure the impact of (de-)compression so I opted for LZ4 which compressed plenty for our needs.  Feel free to challenge this assumption.

Integer Delta Encoding:

Values in this category are almost always the same value (e.g. 0).  From testing delta encoding offers the best performance.

- `click_is_dead`
- `click_is_rage`
- `is_archived`

Integer Double Delta Encoding:

Values in this category increment but not predictably.  Double Delta encoding provided the best compression.

- `project_id` almost always the same value as the previous value.
- `offset` almost always the same value as the previous value.
- `timestamp` almost always the same value as the previous value.

Integer T64 Encoding:

Though segment_id is monotonically increasing for a replay_id, on disk the value is essentially random within the bounds of 0 to 720 with most not exceeding ~20.  Compression here is just okay.  Roughly 3x.

- `segment_id`

Float Gorilla Encoding:

These values rarely change (if at all). Gorilla offers very good compression for static floats.

- `error_sample_rate`
- `session_sample_rate`

### CODE REVIEW

**Comment by evanh** [comment]
Have you done any experimentation to see what benefits this actually provides? I believe this would cause rewriting all the data on disk for these columns.

**Comment by cmanallen** [comment]
@evanh Simple tests like this:

```sql
CREATE TABLE default.replays_test
    (
        `project_id` UInt64,
        `timestamp` DateTime,
        `replay_id` UUID,
        `segment_id` UInt32,
        `random_number_0` UInt16,
        `random_number_1` UInt16 CODEC(Delta, LZ4),
        `random_number_2` UInt16 CODEC(DoubleDelta, LZ4),
        `random_number_3` UInt16 CODEC(Gorilla, LZ4),
        `random_number_4` UInt16 CODEC(T64, LZ4),
        `random_number_5` UInt16 CODEC(Delta, ZSTD),
        `random_number_6` UInt16 CODEC(DoubleDelta, ZSTD),
        `random_number_7` UInt16 CODEC(Gorilla, ZSTD),
        `random_number_8` UInt16 CODEC(T64, ZSTD)
    )
    ENGINE = ReplacingMergeTree
    ORDER BY (project_id, timestamp, replay_id, segment_id)
```

Rinse and repeat for different data layouts.  I saw good compression ratios for this.  2-3 orders of magnitude (not for random numbers though which was 2-3x).

**Comment by evanh** [comment]
I'd love to see the numbers if you can link me to them.

Also about my earlier comment:
> I believe this would cause rewriting all the data on disk for these columns.

Another thing: you are trying to change the encoding of keys in the

**Comment by cmanallen** [comment]
@evanh 

> you can't modify the columns that are in the sorting key of the table (project_id) for example.

Thanks for catching this.  I'll get it removed :D

**Comment by cmanallen** [comment]
@evanh @nikhars Benchmarking results.

# Numeric Encodings

Test table:

```sql
CREATE TABLE default.replays_test
(
    `project_id` UInt64,
    `timestamp` DateTime,
    `replay_id` UUID,
    `segment_id` UInt32,
    `static_number` UInt8,
    `static_number_cmp` UInt8 CODEC(ZSTD),
    `static_number_d_cmp` UInt8 CODEC(Delta, ZSTD),
    `static_number_dd_cmp` UInt8 CODEC(DoubleDelta, ZSTD),
    `rarely_different` UInt8,
    `rarely_different_cmp` UInt8 CODEC(ZSTD),
    `rarely_different_d_cmp` UInt8 CODEC(Delta, ZSTD),
    `rarely_different_dd_cmp` UInt8 CODEC(DoubleDelta, ZSTD),
    `sometimes_different` UInt8,
    `sometimes_different_cmp` UInt8 CODEC(ZSTD),
    `sometimes_different_d_cmp` UInt8 CODEC(Delta, ZSTD),
    `sometimes_different_dd_cmp` UInt8 CODEC(DoubleDelta, ZSTD),
    `static_float` Float64,
    `static_float_gorilla` Float64 CODEC(Gorilla, ZSTD),
    `static_float_cmp` Float64 CODEC(ZSTD)
)
ENGINE = ReplacingMergeTree
ORDER BY (project_id, timestamp, replay_id, segment_id)
```

Tested on 1 million row data set.

Legend:

- "dd" Double delta
- "d" Delta
- "cmp" ZSTD

**Data Set 1**

Rarely different = 1% of events
Sometimes different = 25% of events

```
┌─name───────────────────────┬─compressed_size─┬─uncompressed_size─┬───ratio─┐
│ static_number              │ 4.38 KiB        │ 976.56 KiB        │  223.11 │
│ static_number_dd_cmp       │ 1.03 KiB        │ 976.56 KiB        │  946.97 │
│ static_number_d_cmp        │ 1.03 KiB        │ 976.56 KiB        │  947.87 │
│ static_number_cmp          │ 719.00 B        │ 976.56 KiB        │ 1390.82 │
│────────────────────────────────────────────────────────────────────────────│
│ sometimes_different        │ 513.33 KiB      │ 976.56 KiB        │     1.9 │
│ sometimes_different_dd_cmp │ 207.64 KiB      │ 976.56 KiB        │     4.7 │
│ sometimes_different_d_cmp  │ 195.73 KiB      │ 976.56 KiB        │    4.99 │
│ sometimes_different_cmp    │ 182.57 KiB      │ 976.56 KiB        │    5.35 │
│────────────────────────────────────────────────────────────────────────────│
│ rarely_different           │ 54.40 KiB       │ 976.56 KiB        │   17.95 │
│ rarely_different_d_cmp     │ 26.62 KiB       │ 976.56 KiB        │   36.69 │
│ rarely_different_dd_cmp    │ 24.10 KiB       │ 976.56 KiB        │   40.53 │
│ rarely_different_cmp       │ 21.90 KiB       │ 976.56 KiB        │    44.6 │
│────────────────────────────────────────────────────────────────────────────│
│ static_float               │ 35.80 KiB       │ 7.63 MiB          │  218.22 │
│ static_float_gorilla       │ 8.77 KiB        │ 7.63 MiB          │  891.17 │
│ static_float_cmp           │ 6.49 KiB        │ 7.63 MiB          │ 1204.64 │
└────────────────────────────┴─────────────────┴───────────────────┴─────────┘
```

**Data Set 2**

Rarely different = 0.1% of events
Sometimes different = 2.5% of events

```
┌─name────────────────────────┬─compressed_size─┬─uncompressed_size─┬───ratio─┐
│ static_number               │ 4.38 KiB        │ 976.56 KiB        │  223.11 │
│ static_number_dd_zstd       │ 1.03 KiB        │ 976.56 KiB        │  946.97 │
│ static_number_d_zstd        │ 1.03 KiB        │ 976.56 KiB        │  947.87 │
│ static_number_zstd          │ 719.00 B        │ 976.56 KiB        │ 1390.82 │
│─────────────────────────────────────────────────────────────────────────────│
│ sometimes_different         │ 505.99 KiB      │ 976.56 KiB        │    1.93 │
│ sometimes_different_dd_zstd │ 203.41 KiB      │ 976.56 KiB        │     4.8 │
│ sometimes_different_d_zstd  │ 193.99 KiB      │ 976.56 KiB        │    5.03 │
│ sometimes_different_zstd    │ 181.08 KiB      │ 976.56 KiB        │    5.39 │
│─────────────────────────────────────────────────────────────────────────────│
│ rarely_different            │ 9.49 KiB        │ 976.56 KiB        │  102.86 │
│ rarely_different_dd_zstd    │ 5.37 KiB        │ 976.56 KiB        │  181.98 │
│ rarely_different_d_zstd     │ 4.60 KiB        │ 976.56 KiB        │  212.09 │
│ rarely_different_zstd       │ 2.83 KiB        │ 976.56 KiB        │  344.47 │
│─────────────────────────────────────────────────────────────────────────────│
│ static_float                │ 35.80 KiB       │ 7.63 MiB          │  218.22 │
│ static_float_gorilla        │ 8.77 KiB        │ 7.63 MiB          │  891.17 │
│ static_float_zstd           │ 6.49 KiB        │ 7.63 MiB          │ 1204.64 │
└─────────────────────────────┴─────────────────┴───────────────────┴─────────┘
```

**Query Performance**

```
┌──────mem─┬─duration_ms─┬─query─────────────────────────────────────────────────────────────┐
│ 28295274 │          21 │ SELECT ... HAVING sum(static_number = 0) > 0 LIMIT 1              │
│ 19851395 │          17 │ SELECT ... HAVING sum(static_number_dd_cmp = 0) > 0 LIMIT 1       │
│ 23159007 │          16 │ SELECT ... HAVING sum(static_number_cmp = 0) > 0 LIMIT 1          │
│ 23155577 │          12 │ SELECT ... HAVING sum(static_number_d_cmp = 0) > 0 LIMIT 1        │
│────────────────────────────────────────────────────────────────────────────────────────────│
│ 22311711 │          13 │ SELECT ... HAVING sum(sometimes_different_dd_cmp = 0) > 0 LIMIT 1 │
│ 18093694 │          12 │ SELECT ... HAVING sum(sometimes_different_cmp = 0) > 0 LIMIT 1    │
│ 17891356 │          12 │ SELECT ... HAVING sum(sometimes_different = 0) > 0 LIMIT 1        │
│ 22282805 │           9 │ SELECT ... HAVING sum(sometimes_different_d_cmp = 0) > 0 LIMIT 1  │
│────────────────────────────────────────────────────────────────────────────────────────────│
│ 18618975 │          11 │ SELECT ... HAVING sum(rarely_different_dd_cmp = 0) > 0 LIMIT 1    │
│ 18261106 │           9 │ SELECT ... HAVING sum(rarely_different = 0) > 0 LIMIT 1           │
│ 23165353 │           9 │ SELECT ... HAVING sum(rarely_different_cmp = 0) > 0 LIMIT 1       │
│ 23166190 │           8 │ SELECT ... HAVING sum(rarely_different_d_cmp = 0) > 0 LIMIT 1     │
│ 23184945 │           8 │ SELECT ... HAVING sum(rarely_different = 0) > 0 LIMIT 1           │
│────────────────────────────────────────────────────────────────────────────────────────────│
│ 22622030 │          11 │ SELECT ... HAVING sum(static_float_gorilla = 0) > 0 LIMIT 1       │
│ 22619561 │           9 │ SELECT ... HAVING sum(static_float_cmp = 0) > 0 LIMIT 1           │
│ 22642247 │           9 │ SELECT ... HAVING sum(static_float = 0) > 0 LIMIT 1               │
└──────────┴─────────────┴───────────────────────────────────────────────────────────────────┘
```

**Comment by evanh** [comment]
The query performance doesn't seem much better for the encoded versions of the columns (except for the static case). Given that, do you still want to go forwards with this? Disk storage is generally very cheap compare to compute costs, so if this isn't going to improve the performance I don't know if it's worth it.

**Comment by cmanallen** [comment]
@evanh I think we should close it.  The best compression came from encoding timestamp and project_id but those are part of the primary key which we can't migrate.  I didn't bother testing them again for that reason lol.

**Pull request closed without merging**
