### PR TITLE
fix(discover) Move http_method and http_referer to common fields

### PR DESCRIPTION
**Pull request by evanh**
These columns are now present in events and transactions (and errors) so move
them to the common columns so they can be properly accessed by Discover.

### CODE REVIEW

**Review by markstory — COMMENTED** [review]
Looks good to me.

**Comment by lynnagara** [comment]
Please remove these lines too https://github.com/getsentry/snuba/blob/master/snuba/datasets/discover.py#L316-L317

**Comment by evanh** [comment]
> Please remove these lines too https://github.com/getsentry/snuba/blob/master/snuba/datasets/discover.py#L316-L317

@lynnagara I thought I did? Is there another place I should remove them?

**Comment by lynnagara** [comment]
@evanh Sorry, I can't read the diff properly, you're right

**Review by lynnagara — APPROVED** [review]

**Pull request merged**
