### PR TITLE
feat: Add query support for pre-aggregated sessions (2/4)

### PR DESCRIPTION
**Pull request by Swatinem**
The next step after #1455.

This adds query support which combines both the old `count` based and the new `sum` based columns.
This also adds new quantiles and `avg` for durations.

### CODE REVIEW

**Comment by fpacifici** [comment]
Could you please expand on _"The problem with this is that querying duration_avg gives me a literal NaN, making the JSON invalid."_

Specifically, what is in your table when that happens and what query is snuba running on clickhouse ?
in order to see the query you can either run snuba in debug mode and look into the logs or switch the `STATS_IN_RESPONSE` setting to True and run a query from the web interface: `http://localhost:1218/sessions/query`

In order to check what is in the clickhouse table you need to run the clickhouse client (`clickhouse-client`) on the clickhouse docker container. Then you have a SQL interface on clickhouse.

**Comment by Swatinem** [comment]
The problem I’m describing, and I have this even without my migration / query changes:

When I run the following query:
```sql
SELECT
	started,
	release,
	(quantilesIfMerge(0.5, 0.75, 0.9, 0.95, 0.99)(duration_quantiles) AS duration_quantiles),
	(plus(countIfMerge(sessions), sumIfMerge(sessions_sum)) AS sessions),
	(plus(countIfMerge(sessions_crashed), sumIfMerge(sessions_crashed_sum)) AS sessions_crashed),
	(plus(uniqIfMerge(sessions_errored), sumIfMerge(sessions_errored_sum)) AS sessions_errored),
	(uniqIfMerge(users) AS users),
	(uniqIfMerge(users_crashed) AS users_crashed)
FROM
	sessions_hourly_local PREWHERE in(project_id, tuple(1))
WHERE equals(org_id, 1) AND greaterOrEquals(started, toDateTime('2020-11-05 15:00:00', 'Universal'))
GROUP BY (started, release)
```

When I haven’t ingested any sessions with a duration (the `if` condition is never hit), I get the following output:

```text
started            |release             |duration_quantiles   |sessions|sessions_crashed|sessions_errored|users|users_crashed|
-------------------|--------------------|---------------------|--------|----------------|----------------|-----|-------------|
2020-11-05 17:00:00|test-example-release|[NaN,NaN,NaN,NaN,NaN]|1       |0               |0               |1    |0            |
2020-11-05 16:00:00|test-example-release|[NaN,NaN,NaN,NaN,NaN]|1       |0               |0               |1    |0            |
```

And the output is returned by snuba the same way as JSON:

```json
{"started": "2020-11-05T16:00:00+00:00", "release": "test-example-release", "duration_quantiles": [NaN, NaN, NaN, NaN, NaN], "sessions": 1, "sessions_crashed": 0, "sessions_errored": 0, "users": 1, "users_crashed": 0}
```

Since `NaN` is not a valid JSON value, that makes the whole json invalid.

According to armin, the sentry python backend can still parse and work with that correctly however.

Just wanted to highlight that the newly added `duration_avg` column suffers from the same problem. But like I said, its a big that’s already present in `master` right now.

**Comment by fpacifici** [comment]
There is still one thing I am missing here. What is in the `duration_quantiles` in the materialized view ? Is there a valid state? Could you avoid the group by statement to double check? The issue I would like to verify is whether this is due to having no adta in that bucket or invalid data in that bucket.
Also what happens when we try to aggregate across buckets when one has no/invalid data and the other has valid data? Do we get a NaN ? Because in such case we would have a huge problem.

Also does this ever happen in columns that you are summing up with others ? NaN + something will likely be NaN

**Comment by Swatinem** [comment]
removing the group_by, I do get the correct results.

I think this is expected behavior in clickhouse.

See https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/combinators/#agg-functions-combinator-ordefault
running this query:
```sql
select quantiles(0.5, 0.9)(number), avg(number) from numbers(0)
```
I get:
```text
quantiles(0.5, 0.9)(number)|avg(number)|
---------------------------|-----------|
[NaN,NaN]                  |        NaN|
```

So if there is no input for an aggregate function, it will just return `NaN`, which snuba outputs into the JSON, making it invalid.

**Comment by Swatinem** [comment]
hm, I think this is actually a python problem:

```shell
$ python -c "import json; import math; print(json.dumps({'inf': math.inf, 'nan': math.nan}))"
{"inf": Infinity, "nan": NaN}
```
interestingly, python can `json.loads` that invalid json, but other tools that are strictly will fail.

**Comment by mitsuhiko** [comment]
This works as designed kinda. The only consumer is Python and we depend on `NaN`s making its way across the "extended" JSON.

**Review by fpacifici — COMMENTED** [review]
This seems good to me. As soon as we have a decision on the columns to add in #1455, that one is merged and the migration is applied in production, this can be accepted.

**Review by fpacifici — APPROVED** [review]
Please ensure you run all snuba sentry tests against your snuba source before merging this. This is going to impact the production behavior of the existing session product.

**Comment by Swatinem** [comment]
> Please ensure you run all snuba sentry tests against your snuba source before merging this.

Thanks for reminding me.
I had some errors at first, but re-running solved those. So lets merge this and continue with the next PR ;-)

**Pull request merged**
