### PR TITLE
fix(errors) Disable replacements in errors dataset

### PR DESCRIPTION
**Pull request by fpacifici**
The replacement topic still does not exists for the errors dataset so we need to skip this phase fir now.

### CODE REVIEW

**Review by tkaemming — APPROVED** [review]
I'm assuming we're going to truncate this and restart the consumers before we actually use this?

**Comment by fpacifici** [comment]
`I'm assuming we're going to truncate this and restart the consumers before we actually use this?` Do you mean, truncate the table ?

**Comment by tkaemming** [comment]
> Do you mean, truncate the table ?

Yes, because all of the contents will not have had replacements run on them.

**Comment by fpacifici** [comment]
Oh yes, sure, we are running this now before the replacements are ready to validate the processor works and the schema is right

**Pull request merged**
